// Localization/String+Localized.swift
// 字符串本地化
// 用 L("key") 调用，自动从 LocalizationManager.shared.language 查表

import Foundation
import SwiftUI

/// 简化的本地化函数
/// - Parameter key: 字符串 key
/// - Returns: 当前语言的翻译文本，若无翻译则返回 key 本身
func L(_ key: String) -> String {
    LocalizationManager.shared.localized(key)
}

extension String {
    /// 带参数格式化的本地化
    /// 例如: "起始: %d".localized(with: 5) => 当前语言下的 "起始: 5"
    func localized(with arguments: CVarArg...) -> String {
        let template = L(self)
        return withVaList(arguments) { ptr in
            NSString(format: template, arguments: ptr) as String
        }
    }
}

extension LocalizationManager {
    /// 查表翻译
    func localized(_ key: String) -> String {
        let table = Self.translationTable[language] ?? Self.translationTable[.english] ?? [:]
        return table[key] ?? key
    }

    /// 全部翻译表（key -> 各语言翻译）
    static let translationTable: [AppLanguage: [String: String]] = [
        .simplifiedChinese: [
            "key": "key",
            "专辑": "专辑",
            "从 .smelody.txt 文件导入歌曲": "从 .smelody.txt 文件导入歌曲",
            "副本": "副本",
            "备份曲目库": "备份曲目库",
            "导出歌词": "导出歌词",
            "将删除注音": "将删除注音",
            "将清除 %d 条手动注音": "将清除 %d 条手动注音",
            "将清除 %d 条自动注音": "将清除 %d 条自动注音",
            "将覆盖 %d 条现有的自动注音": "将覆盖 %d 条现有的自动注音",
            "展开元信息": "展开元信息",
            "展开元信息（语言/BPM/调式/标签）": "展开元信息（语言/BPM/调式/标签）",
            "折叠": "折叠",
            "文件格式无效": "文件格式无效",
            "新歌曲": "新歌曲",
            "标签": "标签",
            "缺少歌曲元信息": "缺少歌曲元信息",
            "自动注音（仅日语段落）": "自动注音（仅日语段落）",
            "读取失败": "读取失败",
            "重新生成自动注音": "重新生成自动注音",
            "长按段落任意位置可拖动重排": "长按段落任意位置可拖动重排",
            "上移至顶部": "上移至顶部",
            "下移至底部": "下移至底部",
            "段落拖动": "段落拖动",
            "段落拖动开关说明": "开启后可按住段落任意位置拖动重排：拖到目标段上半插入其前、下半插入其后；拖到列表顶部会自动向上滚动。开启期间左滑删除关闭。歌词编辑栏不会再把段落编号写入正文。",
            "开启段落拖动功能？": "开启段落拖动功能？",
            "我已知晓风险，继续开启": "继续开启",
            "继续开启": "继续开启",
            "拖动段落重排": "拖动段落重排",

            // ====== 段落类型预设（v1.4） ======
            "section.type.Intro"      : "前奏",
            "section.type.Verse"      : "主歌",
            "section.type.Pre-Chorus" : "预副歌",
            "section.type.Chorus"     : "副歌",
            "section.type.Post-Chorus": "副歌后",
            "section.type.Bridge"     : "桥段",
            "section.type.Hook"       : "记忆点",
            "section.type.Refrain"    : "叠句",
            "section.type.Interlude"  : "间奏",
            "section.type.Solo"       : "独奏",
            "section.type.Outro"      : "尾奏",
            "section.type.Coda"       : "终曲",
            "section.type.Custom"     : "自定义",
            // ====== 灵感类型预设（v1.4） ======
            "idea.type.Inspiration"   : "灵感",
            "idea.type.Setting"       : "设定",
            "idea.type.Background"    : "背景",
            "idea.type.Note"          : "备注",

// ====== v1.5 新增 ======
            "笔记": "笔记",
            "译文": "译文",
            "段落译文": "段落译文",
            "更多": "更多",
            "中文": "中文",
            "文件夹": "文件夹",
            "新文件夹": "新文件夹",
            "归并到文件夹": "归并到文件夹",
            "重命名": "重命名",
            "解散文件夹": "解散文件夹",
            "备份文件夹": "备份文件夹",
            "导出文件夹": "导出文件夹",
            "选中 %d 项": "选中 %d 项",
            "已选中": "已选中",
            "取消选择": "取消选择",
            "选择歌曲": "选择歌曲",
            "目标文件夹": "目标文件夹",
            "新建文件夹": "新建文件夹",
            "歌单": "歌单",
            "歌曲类型": "歌曲类型",
            "回收站": "回收站",
            "移到回收站": "移到回收站",
            "永久删除": "永久删除",
            "将歌曲移到回收站": "将歌曲移到回收站？",
            "将歌曲永久删除": "将歌曲永久删除？此操作不可恢复！",
            "将文件夹永久删除": "将永久删除文件夹及其中所有歌曲？此操作不可恢复！",
            "清空回收站": "清空回收站",
            "在回收站中再次删除才能永久删除": "在回收站中再次删除才能永久删除",
            "已选 %d 项": "已选 %d 项",
            "已选 1 项": "已选 1 项",
            // ====== v1.6 节拍 / 文件夹操作 ======
            "节拍": "节拍",
            "节拍器": "节拍器",
            "停止": "停止",
            "停止节拍器": "停止节拍器",
            "启动节拍器": "启动节拍器",
            // ====== v1.7 歌词预览 / UI补充 ======
            "歌词预览": "歌词预览",
            "预览歌词": "预览歌词",
            "未命名歌曲": "未命名歌曲",
            "未知艺术家": "未知艺术家",
            "暂无歌词": "暂无歌词",
            "双击跳转到段落": "双击跳转到该段落",
            "正在预览": "正在预览",
            "展开 / 收起元信息": "展开 / 收起元信息",

            "删除文件夹": "删除文件夹",
            "双击展开/折叠文件夹": "双击展开/折叠文件夹",
            "确定要删除文件夹": "确定要删除文件夹？",

            "备份曲目库（含文件夹结构）": "备份曲目库（含文件夹结构）",

            // ====== v1.5.2 批量操作 ======
            "批量导出": "批量导出",
            "批量移到回收站": "批量移到回收站",
            "批量恢复": "批量恢复",
            "批量永久删除": "批量永久删除",
            "批量移到根目录": "批量移到根目录",
            "移到根目录": "移到根目录",
            "移到其他文件夹": "移到其他文件夹",
            "批量移到其他文件夹": "批量移到其他文件夹",
            "合并到新文件夹": "合并到新文件夹",
            "合并到文件夹": "合并到文件夹",
            "将 %d 首歌曲移到回收站？": "将 %d 首歌曲移到回收站？",
            "导入 .smelody.txt 文件（可多选）": "导入 .smelody.txt 文件（可多选）",
            "导入文件夹（不递归套娃，归到同名文件夹）": "导入文件夹（不递归套娃，归到同名文件夹）",
            "批量导入文件夹": "批量导入文件夹",
            "选择要导入的 .smelody.txt 文件（可多选）": "选择要导入的 .smelody.txt 文件（可多选）",
            "导入文件夹": "导入文件夹",
            "导入备份文件夹（含套娃结构）": "导入备份文件夹（含套娃结构）",
            "导入成功 (%d 首歌曲)": "导入成功 (%d 首歌曲)",
            "输入文件夹名": "输入文件夹名",
            "输入新文件夹名": "输入新文件夹名",
            "套娃文件夹": "套娃文件夹",

            // ====== 通用 ======
            "确定": "确定",
            "取消": "取消",
            "歌词导出": "歌词导出",
            "歌曲信息": "歌曲信息",
            "歌词": "歌词",
            "创建时间": "创建时间",
            "修改时间": "修改时间",
            "导出时间": "导出时间",
            "请先在歌曲语言中加入日语": "请先在歌曲语言中加入日语",
            "导出为文本文件（含全部信息）": "导出为文本文件（含全部信息）",
            "将歌词的全部信息导出为文本文件": "将歌词的全部信息导出为文本文件",
            "导入歌曲": "导入歌曲",
            "导入歌曲文件": "导入歌曲文件",
            "选择要导入的 .smelody.txt 文件": "选择要导入的 .smelody.txt 文件",
            "导入成功": "导入成功",
            "导入失败": "导入失败",
            "数据管理": "数据管理",
            "一键备份曲目库": "一键备份曲目库",
            "将所有歌曲按 .smelody.txt 格式打包到选定文件夹": "将所有歌曲按 .smelody.txt 格式打包到选定文件夹",
            "备份": "备份",
            "成功备份 %d 首歌曲到\n%@": "成功备份 %d 首歌曲到\n%@",
            "成功 %d 首，失败 %d 首": "成功 %d 首，失败 %d 首",
            "选择保存备份的文件夹": "选择保存备份的文件夹",
            "选择这里": "选择这里",
            "删除前显示确认弹窗": "删除前显示确认弹窗",
            "删除歌曲、段落、灵感前提示确认（暂不可恢复）": "删除歌曲、段落、灵感前提示确认（暂不可恢复）",
            "确认删除": "确认删除",
            "此操作暂不可恢复": "此操作暂不可恢复",
            "不再提醒（可在设置中重新开启）": "不再提醒（可在设置中重新开启）",
            "将删除歌曲": "将删除歌曲",
            "将删除段落": "将删除段落",
            "将删除条目": "将删除条目",
            "将删除 %d 个段落": "将删除 %d 个段落",
            "包含": "包含",
            "个段落": "个段落",
            "条灵感与设定": "条灵感与设定",
            "条译文": "条译文",
            "帮助": "帮助",
            "下载链接": "下载链接",
            "检查版本更新": "检查版本更新",
            "启动时检查更新": "启动时检查更新",
            "启动时检查更新说明": "每次启动静默检查 GitHub 发布；仅在有新版本时弹窗。",
            "发现新版本": "发现新版本",
            "前往下载": "前往下载",
            "稍后": "稍后",
            "已是最新版本": "已是最新版本",
            "检查更新失败": "检查更新失败",
            "正在检查更新": "正在检查更新",
            "预览段落小字": "预览段落小字",
            "预览段落小字说明": "歌词预览里每段正文下方的说明文字，可在笔记与译文之间切换；空内容不显示。",
            "更新日志": "更新日志",
            "查看更新日志": "查看更新日志",
            "查看每个版本的更新内容": "查看每个版本的更新内容",
            "最新": "最新",
            "使用指南": "使用指南",
            "软件介绍 + 各功能使用说明（随界面语言切换）": "软件介绍 + 各功能使用说明",
            "技能炼成": "技能炼成",
            "技能煉成": "技能煉成",
            "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用": "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用",
            "Skill Integrated": "Skill Integrated",
            "スキル錬成": "スキル錬成",
            "词炼成": "词炼成",
            "曲炼成": "曲炼成",
            "导出 Skill 文件": "导出 Skill 文件",
            "复制到剪贴板": "复制到剪贴板",
            "Skill 简介": "Skill 简介",
            "smelody-lyric-create": "smelody-lyric-create",
            "smelody-music-create": "smelody-music-create",
            "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）": "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）",
            "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）": "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）",
            "保存为": "保存为",
            "保存": "保存",
            "保存成功": "保存成功",
            "保存失败": "保存失败",
            "：找不到 SKILL.md 资源": "：找不到 SKILL.md 资源",
            "复制成功": "复制成功",
            "复制失败": "复制失败",
            "选择保存位置": "选择保存位置",
            "Skill 文件（.md）": "Skill 文件（.md）",
            "Skill 文件夹父目录": "Skill 文件夹父目录",
            "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。": "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。",
            "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。": "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。",
            "典型工作流": "典型工作流",
            "完整工作流（推荐）": "完整工作流（推荐）",
            "第一步：做词炼成": "第一步：做词炼成",
            "第二步：做曲炼成": "第二步：做曲炼成",
            "第三步：交给 AI Agent 作曲": "第三步：交给 AI Agent 作曲",
            "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）": "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）",
            "描述歌曲主题、风格、参考等": "描述歌曲主题、风格、参考等",
            "触发词：": "触发词：",
            "触发词": "触发词",
            "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"": "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"",
            "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"": "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"",
            "输出": "输出",
            "把完整歌词文件保存为 .smelody.txt": "把完整歌词文件保存为 .smelody.txt",
            "在 Simple Melody 中导入": "在 Simple Melody 中导入",
            "把 .smelody.txt 歌词文件发给 AI Agent": "把 .smelody.txt 歌词文件发给 AI Agent",
            "AI 提炼出两段式输出文件": "AI 提炼出两段式输出文件",
            "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框": "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框",
            "下半部分作曲建议作为 Style prompt 的一部分": "下半部分作曲建议作为 Style prompt 的一部分",
            "如果您无法理解以上内容请不要使用该功能": "如果您无法理解以上内容请不要使用该功能",
            "Skill需要移交给有文件处理能力的LLM": "Skill需要移交给有文件处理能力的LLM",
            "否则无效": "否则无效",
            "血红色警示": "血红色警示",
            "复制 Skill 文本": "复制 Skill 文本",
            "已复制到剪贴板": "已复制到剪贴板",
            "词炼成：AI 输出完整 .smelody.txt": "词炼成：AI 输出完整 .smelody.txt",
            "曲炼成：AI 输出两段式（歌词 + 作曲建议）": "曲炼成：AI 输出两段式（歌词 + 作曲建议）",
            "删除": "删除",
            "编辑": "编辑",
            "新建": "新建",
            "搜索": "搜索",
            "关闭": "关闭",
            "复制": "复制",
            "粘贴": "粘贴",
            "导出": "导出",
            "导入": "导入",

            // ====== 主界面 ======
            "曲目库": "曲目库",
            "首": "首",
            "条记录": "条记录",
            "搜索曲目": "搜索曲目",
            "新建歌曲": "新建歌曲",
            "新建第一首": "新建第一首",
            "新建段落": "新建段落",
            "还没有歌曲": "还没有歌曲",
            "没有匹配的歌曲": "没有匹配的歌曲",
            "选择左侧的歌曲开始创作，或新建一首新歌。": "选择左侧的歌曲开始创作，或新建一首新歌。",
            "Simple Melody": "Simple Melody",

            // 排序
            "排序方式": "排序方式",
            "手动排序": "手动排序",
            "最近修改": "最近修改",
            "标题": "标题",

            // 段落计数等
            "段": "段",
            "字": "字",
            "BPM": "BPM",
            "Key": "Key",
            "未命名": "未命名",

            // ====== 歌曲编辑 ======
            "歌曲标题": "歌曲标题",
            "艺术家": "艺术家",
            "语言": "语言",
            "调式": "调式",
            "标签（逗号分隔）": "标签（逗号分隔）",
            "收起": "收起",
            "展开": "展开",
            "导出为文本文件": "导出为文本文件",
            "复制全文到剪贴板": "复制全文到剪贴板",
            "段落笔记": "段落笔记",
            "段落类型": "段落类型",
            "自定义段落名": "自定义段落名",
            "应用": "应用",
            "如 Spoken Word": "如 Spoken Word",
            "上移": "上移",
            "下移": "下移",
            "复制段落": "复制段落",
            "上": "上",
            "下": "下",

            // ====== 段落类型 ======
            "前奏": "前奏",
            "主歌": "主歌",
            "预副歌": "预副歌",
            "副歌": "副歌",
            "副歌后": "副歌后",
            "桥段": "桥段",
            "记忆点": "记忆点",
            "叠句": "叠句",
            "间奏": "间奏",
            "独奏": "独奏",
            "尾奏": "尾奏",
            "终曲": "终曲",
            "自定义": "自定义",
            "添加段落": "添加段落",

            // ====== 注音 ======
            "正文": "正文",
            "读音摘要": "读音摘要",
            "注音列表": "注音列表",
            "添加读音": "添加读音",
            "自动注音": "自动注音",
            "对日语汉字自动生成假名注音": "对日语汉字自动生成假名注音",
            "为指定位置的文字添加读音": "为指定位置的文字添加读音",
            "清除注音选项": "清除注音选项",
            "清除所有自动注音": "清除所有自动注音",
            "清除所有手动注音": "清除所有手动注音",
            "在正文中的位置": "在正文中的位置",
            "起始: %d": "起始: %d",
            "长度: %d": "长度: %d",
            "原文预览": "原文预览",
            "原文": "原文",
            "假名读音": "假名读音",
            "拼音": "拼音",
            "Phonetic": "Phonetic",
            "编辑读音": "编辑读音",
            "自动标注日语假名": "自动标注日语假名",

            // ====== 灵感分栏 ======
            "灵感与设定": "灵感与设定",
            "灵感": "灵感",
            "设定": "设定",
            "背景": "背景",
            "备注": "备注",
            "全部": "全部",
            "记录灵感、背景故事、设定...": "记录灵感、背景故事、设定...",
            "还没有灵感或设定": "还没有灵感或设定",
            "在这里记录创作灵感、角色设定或背景故事。": "在这里记录创作灵感、角色设定或背景故事。",
            "这些内容不会出现在歌词正文里。": "这些内容不会出现在歌词正文里。",

            // ====== 设置 ======
            "设置": "设置",
            "主题": "主题",
            "字体大小": "字体大小",
            "较小": "较小",
            "较大": "较大",
            "跟随系统": "跟随系统",
            "浅色": "浅色",
            "深色": "深色",
            "界面语言": "界面语言",
            "接入大模型": "接入大模型",
            "供以后的注音、翻译等功能使用": "供以后的注音、翻译等功能使用",
            "供应商网址": "供应商网址",
            "模型名": "模型名",
            "Imagine": "Imagine",
            "段落Imagine": "段落Imagine",
            "翻译": "翻译",
            "创意": "创意",
            "注音": "注音",
            "即将推出": "即将推出",
            "只修改这一段": "只修改这一段",
            "也可填写歌曲语言、速度、调式和节拍": "也可填写歌名、歌曲语言、速度、调式和节拍",
            "提示词可留空": "提示词可留空",
            "目标语言": "目标语言",
            "开始": "开始",
            "继续": "继续",
            "依照当前格式": "依照当前格式",
            "创意可能无法撤销或改错": "创意可能无法撤销或改错",
            "创意会改动歌词，可能无法撤销或出现错误。确定要继续吗？": "创意会改动歌词，可能无法撤销或出现错误。确定要继续吗？",
            "段落Imagine不能改整首歌或其他段落": "段落Imagine不能改整首歌或其他段落",
            "测试连接": "测试连接",
            "连接成功": "连接成功",
            "连接失败": "连接失败",
            "正在测试连接": "正在测试连接",
            "请先填写供应商网址和 API Key": "请先填写供应商网址和 API Key",
            "回复格式无法识别，没有改动歌词": "回复格式无法识别，没有改动歌词",
            "正在请模型处理": "正在请模型处理",
            "按 Command-Esc 取消": "按 Command-Esc 取消",
            "没有歌词的段落不会翻译，笔记也不会被当成歌词": "没有歌词的段落不会翻译，笔记也不会被当成歌词",
            "模型名可以留空": "模型名可以留空",
            "建议选用参数量更大的模型，以便翻译、注音和创作更准确": "建议选用参数量更大的模型，以便翻译、注音和创作更准确",
            "API Key": "API Key",
            "清除": "清除",
            "首选语言": "首选语言",
            "歌曲语言（可多选）": "歌曲语言（可多选）",

            // ====== 歌曲语言名称（多选 chip） ======
            "日语": "日语",
            "简体中文": "简体中文",
            "繁体中文": "繁体中文",
            "英语": "英语",
            "韩语": "韩语",
            "西班牙语": "西班牙语",
            "法语": "法语",
            "德语": "德语",
            "意大利语": "意大利语",
            "葡萄牙语": "葡萄牙语",
            "选择语言": "选择语言",
            "已选": "已选",
            "未选": "未选",
            "歌词语言": "歌词语言",
            "自动识别系统语言": "自动识别系统语言",
            "应用启动时检测系统语言": "应用启动时检测系统语言",

            // ====== 菜单 ======
            "Simple Melody 帮助": "Simple Melody 帮助",

            // ====== 通知 ======
            "暂无帮助文档，请查看 README.md": "暂无帮助文档，请查看 README.md",

            // ====== 版本 ======
            "关于 Simple Melody": "关于 Simple Melody",
            "版本": "版本",
            "v1.1 · Apple Silicon Native": "v1.1 · Apple Silicon Native",

            // ====== 状态 ======
            "灵感分栏": "灵感分栏",
            "显示/隐藏灵感与设定分栏": "显示/隐藏灵感与设定分栏",
            "Apple Silicon 原生": "Apple Silicon 原生",
            "平台": "平台",
            "开发者": "开发者",
            "自动标注日语假音": "自动标注日语假名",
            "批量备份": "批量备份",

        ],

        .traditionalChinese: [
                        "section.type.Intro": "前奏",
            "section.type.Verse": "主歌",
            "section.type.Pre-Chorus": "預副歌",
            "section.type.Chorus": "副歌",
            "section.type.Post-Chorus": "副歌後",
            "section.type.Bridge": "橋段",
            "section.type.Hook": "記憶點",
            "section.type.Refrain": "疊句",
            "section.type.Interlude": "間奏",
            "section.type.Solo": "獨奏",
            "section.type.Outro": "尾奏",
            "section.type.Coda": "終曲",
            "section.type.Custom": "自訂",
            "idea.type.Inspiration": "靈感",
            "idea.type.Setting": "設定",
            "idea.type.Background": "背景",
            "idea.type.Note": "備註",
// ====== v1.5 新增 ======
            "笔记": "筆記",
            "译文": "譯文",
            "段落译文": "段落譯文",
            "更多": "更多",
            "中文": "中文",
            "文件夹": "文件夾",
            "新文件夹": "新檔案夾",
            "归并到文件夹": "歸併到檔案夾",
            "重命名": "重新命名",
            "解散文件夹": "解散檔案夾",
            "备份文件夹": "備份檔案夾",
            "导出文件夹": "匯出檔案夾",
            "选中 %d 项": "已選 %d 項",
            "已选中": "已選中",
            "取消选择": "取消選取",
            "选择歌曲": "選擇歌曲",
            "目标文件夹": "目標檔案夾",
            "新建文件夹": "新建檔案夾",
            "歌单": "歌單",
            "歌曲类型": "歌曲類型",
            "回收站": "回收桶",
            "移到回收站": "移到回收桶",
            "永久删除": "永久刪除",
            "将歌曲移到回收站": "將歌曲移到回收桶？",
            "将歌曲永久删除": "將歌曲永久刪除？此操作不可復原！",
            "将文件夹永久删除": "將永久刪除檔案夾及其中所有歌曲？此操作不可復原！",
            "清空回收站": "清空回收桶",
            "在回收站中再次删除才能永久删除": "在回收桶中再次刪除才能永久刪除",
            "已选 %d 项": "已選 %d 項",
            "已选 1 项": "已選 1 項",
            // ====== v1.6 节拍 / 文件夹操作 ======
            "节拍": "節拍",
            "节拍器": "節拍器",
            "停止": "停止",
            "停止节拍器": "停止節拍器",
            "启动节拍器": "啟動節拍器",
            // ====== v1.7 歌词预览 / UI补充 ======
            "歌词预览": "歌詞預覽",
            "预览歌词": "預覽歌詞",
            "未命名歌曲": "未命名歌曲",
            "未知艺术家": "未知藝術家",
            "暂无歌词": "暫無歌詞",
            "双击跳转到段落": "雙擊跳轉到該段落",
            "正在预览": "正在預覽",
            "展开 / 收起元信息": "展開 / 收起元信息",

            "删除文件夹": "刪除檔案夾",
            "双击展开/折叠文件夹": "雙擊展開/折疊檔案夾",
            "确定要删除文件夹": "確定要刪除檔案夾？",

            "备份曲目库（含文件夹结构）": "備份歌單庫（含檔案夾結構）",
            "导入文件夹": "匯入檔案夾",
            // ====== v1.5.2 批量操作 ======
            "批量导出": "批量匯出",
            "批量移到回收站": "批量移到回收桶",
            "批量恢复": "批量恢復",
            "批量永久删除": "批量永久刪除",
            "批量移到根目录": "批量移到根目錄",
            "移到根目录": "移到根目錄",
            "移到其他文件夹": "移到其他資料夾",
            "批量移到其他文件夹": "批量移到其他資料夾",
            "合并到新文件夹": "合併到新檔案夾",
            "合并到文件夹": "合併到檔案夾",
            "将 %d 首歌曲移到回收站？": "將 %d 首歌曲移到回收桶？",
            "导入 .smelody.txt 文件（可多选）": "匯入 .smelody.txt 文件（可多選）",
            "导入文件夹（不递归套娃，归到同名文件夹）": "匯入檔案夾（不遞歸套娃，歸到同名檔案夾）",
            "批量导入文件夹": "批量匯入檔案夾",
            "选择要导入的 .smelody.txt 文件（可多选）": "選擇要匯入的 .smelody.txt 文件（可多選）",

            "导入备份文件夹（含套娃结构）": "匯入備份檔案夾（含套娃結構）",
            "导入成功 (%d 首歌曲)": "匯入成功（%d 首歌曲）",
            "输入文件夹名": "輸入檔案夾名",
            "输入新文件夹名": "輸入新檔案夾名",
            "套娃文件夹": "套娃檔案夾",

"确定": "確定",
            "取消": "取消",
            "歌词导出": "歌詞匯出",
            "歌曲信息": "歌曲資訊",
            "歌词": "歌詞",
            "创建时间": "建立時間",
            "修改时间": "修改時間",
            "导出时间": "匯出時間",
            "请先在歌曲语言中加入日语": "請先在歌曲語言中加入日語",
            "导出为文本文件（含全部信息）": "匯出為文字檔（含全部資訊）",
            "将歌词的全部信息导出为文本文件": "將歌詞的全部資訊匯出為文字檔",
            "导入歌曲": "匯入歌曲",
            "导入歌曲文件": "匯入歌曲檔案",
            "选择要导入的 .smelody.txt 文件": "選擇要匯入的 .smelody.txt 檔案",
            "导入成功": "匯入成功",
            "导入失败": "匯入失敗",
            "数据管理": "資料管理",
            "一键备份曲目库": "一鍵備份曲目庫",
            "将所有歌曲按 .smelody.txt 格式打包到选定文件夹": "將所有歌曲按 .smelody.txt 格式打包到選定資料夾",
            "备份": "備份",
            "成功备份 %d 首歌曲到\n%@": "成功備份 %d 首歌曲到\n%@",
            "成功 %d 首，失败 %d 首": "成功 %d 首，失敗 %d 首",
            "选择保存备份的文件夹": "選擇儲存備份的資料夾",
            "选择这里": "選擇這裡",
            "删除前显示确认弹窗": "刪除前顯示確認彈窗",
            "删除歌曲、段落、灵感前提示确认（暂不可恢复）": "刪除歌曲、段落、靈感前提示確認（暫不可恢復）",
            "确认删除": "確認刪除",
            "此操作暂不可恢复": "此操作暫不可恢復",
            "不再提醒（可在设置中重新开启）": "不再提醒（可在設定中重新開啟）",
            "将删除歌曲": "將刪除歌曲",
            "将删除段落": "將刪除段落",
            "将删除条目": "將刪除條目",
            "将删除 %d 个段落": "將刪除 %d 個段落",
            "包含": "包含",
            "个段落": "個段落",
            "条灵感与设定": "條靈感與設定",
            "条译文": "條譯文",
            "帮助": "說明",
            "下载链接": "下載連結",
            "检查版本更新": "檢查版本更新",
            "启动时检查更新": "啟動時檢查更新",
            "启动时检查更新说明": "每次啟動靜默檢查 GitHub 發布；僅在有新版本時彈窗。",
            "发现新版本": "發現新版本",
            "前往下载": "前往下載",
            "稍后": "稍後",
            "已是最新版本": "已是最新版本",
            "检查更新失败": "檢查更新失敗",
            "正在检查更新": "正在檢查更新",
            "预览段落小字": "預覽段落小字",
            "预览段落小字说明": "歌詞預覽裡每段正文下方的說明文字，可在筆記與譯文之間切換；空內容不顯示。",
            "更新日志": "更新日誌",
            "查看更新日志": "查看更新日誌",
            "查看每个版本的更新内容": "查看每個版本的更新內容",
            "使用指南": "使用指南",
            "技能炼成": "技能煉成",
            "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用": "把 Simple Melody 的歌詞 Skill 匯出給 AI Agent 用",
            "词炼成": "詞煉成",
            "曲炼成": "曲煉成",
            "导出 Skill 文件": "匯出 Skill 檔案",
            "复制到剪贴板": "複製到剪貼簿",
            "Skill 简介": "Skill 簡介",
            "smelody-lyric-create": "smelody-lyric-create",
            "smelody-music-create": "smelody-music-create",
            "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）": "把創作需求 → 完整的 .smelody.txt（可匯入 Simple Melody）",
            "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）": "把 .smelody.txt → 作曲 AI 輸入（SUNO / Udio）",
            "保存为": "儲存為",
            "保存成功": "儲存成功",
            "保存失败": "儲存失敗",
            "：找不到 SKILL.md 资源": "：找不到 SKILL.md 資源",
            "复制成功": "複製成功",
            "复制失败": "複製失敗",
            "选择保存位置": "選擇儲存位置",
            "Skill 文件（.md）": "Skill 檔案（.md）",
            "Skill 文件夹父目录": "Skill 資料夾父目錄",
            "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。": "詞煉成是把創作需求轉化為可匯入 Simple Melody 的 .smelody.txt 歌詞檔案。",
            "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。": "曲煉成是把 .smelody.txt 提煉為作曲 AI（SUNO / Udio 等）可直接使用的兩段式檔案。",
            "典型工作流": "典型工作流",
            "完整工作流（推荐）": "完整工作流（推薦）",
            "第一步：做词炼成": "第一步：做詞煉成",
            "第二步：做曲炼成": "第二步：做曲煉成",
            "第三步：交给 AI Agent 作曲": "第三步：交給 AI Agent 作曲",
            "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）": "把創作需求發給 AI Agent（如有 SUNO/Udio 工具）",
            "描述歌曲主题、风格、参考等": "描述歌曲主題、風格、參考等",
            "触发词：": "觸發詞：",
            "触发词": "觸發詞",
            "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"": "\"做詞煉成\" / \"按 smelody 格式寫歌詞\" / \"寫一首 Simple Melody 格式的歌詞\"",
            "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"": "\"做曲煉成\" / \"準備 SUNO 提示詞\" / \"整理歌詞給 AI 作曲\"",
            "输出": "輸出",
            "把完整歌词文件保存为 .smelody.txt": "把完整歌詞檔案儲存為 .smelody.txt",
            "在 Simple Melody 中导入": "在 Simple Melody 中匯入",
            "把 .smelody.txt 歌词文件发给 AI Agent": "把 .smelody.txt 歌詞檔案發給 AI Agent",
            "AI 提炼出两段式输出文件": "AI 提煉出兩段式輸出檔案",
            "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框": "上半部分歌詞貼上到 SUNO / Udio 的 Lyrics 輸入框",
            "下半部分作曲建议作为 Style prompt 的一部分": "下半部分作曲建議作為 Style prompt 的一部分",
            "如果您无法理解以上内容请不要使用该功能": "如果您無法理解以上內容請不要使用該功能",
            "Skill需要移交给有文件处理能力的LLM": "Skill需要移交給有檔案處理能力的LLM",
            "否则无效": "否則無效",
            "复制 Skill 文本": "複製 Skill 文字",
            "已复制到剪贴板": "已複製到剪貼簿",
            "词炼成：AI 输出完整 .smelody.txt": "詞煉成：AI 輸出完整 .smelody.txt",
            "曲炼成：AI 输出两段式（歌词 + 作曲建议）": "曲煉成：AI 輸出兩段式（歌詞 + 作曲建議）",
            "软件介绍 + 各功能使用说明（随界面语言切换）": "軟體介紹 + 各功能使用說明",
            "最新": "最新",
            "版本": "版本",
            "开发者": "開發者",
            "平台": "平台",
            "Apple Silicon 原生": "Apple Silicon 原生",
            "保存": "儲存",
            "删除": "刪除",
            "编辑": "編輯",
            "新建": "新增",
            "搜索": "搜尋",
            "关闭": "關閉",
            "复制": "複製",
            "粘贴": "貼上",
            "导出": "匯出",
            "导入": "匯入",

            "曲目库": "曲目庫",
            "首": "首",
            "条记录": "條記錄",
            "搜索曲目": "搜尋曲目",
            "新建歌曲": "新增歌曲",
            "新建第一首": "新增第一首",
            "新建段落": "新增段落",
            "还没有歌曲": "還沒有歌曲",
            "没有匹配的歌曲": "沒有符合的歌曲",
            "选择左侧的歌曲开始创作，或新建一首新歌。": "選擇左側的歌曲開始創作，或新增一首新歌。",
            "Simple Melody": "Simple Melody",

            "排序方式": "排序方式",
            "手动排序": "手動排序",
            "最近修改": "最近修改",
            "标题": "標題",

            "段": "段",
            "字": "字",
            "BPM": "BPM",
            "Key": "Key",
            "未命名": "未命名",

            "歌曲标题": "歌曲標題",
            "艺术家": "藝術家",
            "语言": "語言",
            "调式": "調式",
            "标签（逗号分隔）": "標籤（逗號分隔）",
            "收起": "收起",
            "展开": "展開",
            "导出为文本文件": "匯出為文字檔",
            "复制全文到剪贴板": "複製全文到剪貼簿",
            "段落笔记": "段落筆記",
            "段落类型": "段落類型",
            "自定义段落名": "自訂段落名",
            "应用": "套用",
            "如 Spoken Word": "如 Spoken Word",
            "上移": "上移",
            "下移": "下移",
            "复制段落": "複製段落",
            "上": "上",
            "下": "下",

            "前奏": "前奏",
            "主歌": "主歌",
            "预副歌": "預副歌",
            "副歌": "副歌",
            "副歌后": "副歌後",
            "桥段": "橋段",
            "记忆点": "記憶點",
            "叠句": "疊句",
            "间奏": "間奏",
            "独奏": "獨奏",
            "尾奏": "尾奏",
            "终曲": "終曲",
            "自定义": "自訂",
            "添加段落": "新增段落",

            "正文": "正文",
            "读音摘要": "讀音摘要",
            "注音列表": "注音列表",
            "添加读音": "新增讀音",
            "自动注音": "自動注音",
            "对日语汉字自动生成假名注音": "對日語漢字自動產生假名注音",
            "为指定位置的文字添加读音": "為指定位置的文字新增讀音",
            "清除注音选项": "清除注音選項",
            "清除所有自动注音": "清除所有自動注音",
            "清除所有手动注音": "清除所有手動注音",
            "在正文中的位置": "在正文中的位置",
            "起始: %d": "起始: %d",
            "长度: %d": "長度: %d",
            "原文预览": "原文預覽",
            "原文": "原文",
            "假名读音": "假名讀音",
            "拼音": "拼音",
            "Phonetic": "Phonetic",
            "编辑读音": "編輯讀音",
            "自动标注日语假名": "自動標註日語假名",

            "灵感与设定": "靈感與設定",
            "灵感": "靈感",
            "设定": "設定",
            "背景": "背景",
            "备注": "備註",
            "全部": "全部",
            "记录灵感、背景故事、设定...": "記錄靈感、背景故事、設定...",
            "还没有灵感或设定": "還沒有靈感或設定",
            "在这里记录创作灵感、角色设定或背景故事。": "在這裡記錄創作靈感、角色設定或背景故事。",
            "这些内容不会出现在歌词正文里。": "這些內容不會出現在歌詞正文裡。",

            "设置": "設定",
            "主题": "主題",
            "字体大小": "字體大小",
            "较小": "較小",
            "较大": "較大",
            "跟随系统": "跟隨系統",
            "浅色": "淺色",
            "深色": "深色",
            "界面语言": "介面語言",
            "接入大模型": "接入大型模型",
            "供以后的注音、翻译等功能使用": "供以後的注音、翻譯等功能使用",
            "供应商网址": "供應商網址",
            "模型名": "模型名稱",
            "Imagine": "Imagine",
            "段落Imagine": "段落Imagine",
            "翻译": "翻譯",
            "创意": "創意",
            "注音": "注音",
            "即将推出": "即將推出",
            "只修改这一段": "只修改這一段",
            "也可填写歌曲语言、速度、调式和节拍": "也可填寫歌名、歌曲語言、速度、調式和節拍",
            "提示词可留空": "提示詞可留空",
            "目标语言": "目標語言",
            "开始": "開始",
            "继续": "繼續",
            "依照当前格式": "依照當前格式",
            "创意可能无法撤销或改错": "創意可能無法撤銷或改錯",
            "创意会改动歌词，可能无法撤销或出现错误。确定要继续吗？": "創意會改動歌詞，可能無法撤銷或出現錯誤。確定要繼續嗎？",
            "段落Imagine不能改整首歌或其他段落": "段落Imagine不能改整首歌或其他段落",
            "测试连接": "測試連線",
            "连接成功": "連線成功",
            "连接失败": "連線失敗",
            "正在测试连接": "正在測試連線",
            "请先填写供应商网址和 API Key": "請先填寫供應商網址和 API Key",
            "回复格式无法识别，没有改动歌词": "回覆格式無法識別，沒有改動歌詞",
            "正在请模型处理": "正在請模型處理",
            "按 Command-Esc 取消": "按 Command-Esc 取消",
            "没有歌词的段落不会翻译，笔记也不会被当成歌词": "沒有歌詞的段落不會翻譯，筆記也不會被當成歌詞",
            "模型名可以留空": "模型名稱可以留空",
            "建议选用参数量更大的模型，以便翻译、注音和创作更准确": "建議選用參數量更大的模型，以便翻譯、注音和創作更準確",
            "API Key": "API Key",
            "清除": "清除",
            "首选语言": "首選語言",
            "歌曲语言（可多选）": "歌曲語言（可多選）",

            "日语": "日語",
            "简体中文": "簡體中文",
            "繁体中文": "繁體中文",
            "英语": "英語",
            "韩语": "韓語",
            "西班牙语": "西班牙語",
            "法语": "法語",
            "德语": "德語",
            "意大利语": "意大利語",
            "葡萄牙语": "葡萄牙語",
            "选择语言": "選擇語言",
            "已选": "已選",
            "未选": "未選",
            "歌词语言": "歌詞語言",
            "自动识别系统语言": "自動識別系統語言",
            "应用启动时检测系统语言": "應用啟動時偵測系統語言",

            "Simple Melody 帮助": "Simple Melody 說明",

            "暂无帮助文档，请查看 README.md": "暫無說明文件，請查看 README.md",

            "关于 Simple Melody": "關於 Simple Melody",
            "v1.1 · Apple Silicon Native": "v1.1 · Apple Silicon Native",

            "灵感分栏": "靈感分欄",
            "显示/隐藏灵感与设定分栏": "顯示/隱藏靈感與設定分欄",
            "专辑": "專輯",
            "从 .smelody.txt 文件导入歌曲": "從 .smelody.txt 檔案匯入歌曲",
            "副本": "副本",
            "备份曲目库": "備份曲目庫",
            "导出歌词": "匯出歌詞",
            "将删除注音": "將刪除注音",
            "将清除 %d 条手动注音": "將清除 %d 條手動注音",
            "将清除 %d 条自动注音": "將清除 %d 條自動注音",
            "将覆盖 %d 条现有的自动注音": "將覆蓋 %d 條現有的自動注音",
            "展开元信息": "展開元資訊",
            "展开元信息（语言/BPM/调式/标签）": "展開元資訊（語言/BPM/調式/標籤）",
            "折叠": "折疊",
            "文件格式无效": "檔案格式無效",
            "新歌曲": "新歌曲",
            "标签": "標籤",
            "缺少歌曲元信息": "缺少歌曲元資訊",
            "自动注音（仅日语段落）": "自動注音（僅日語段落）",
            "读取失败": "讀取失敗",
            "重新生成自动注音": "重新產生自動注音",
            "长按段落任意位置可拖动重排": "長按段落任意位置可拖動重排",
            "上移至顶部": "上移至頂部",
            "下移至底部": "下移至底部",
            "段落拖动": "段落拖動",
            "段落拖动开关说明": "開啟後可按住段落任意位置拖動重排：拖到目標段上半插入其前、下半插入其後；拖到列表頂部會自動向上捲動。開啟期間左滑刪除關閉。歌詞編輯欄不會再把段落編號寫入正文。",
            "开启段落拖动功能？": "開啟段落拖動功能？",
            "我已知晓风险，继续开启": "繼續開啟",
            "继续开启": "繼續開啟",
            "拖动段落重排": "拖動段落重排",
            "key": "key",
            "技能煉成": "技能煉成",
            "Skill Integrated": "Skill Integrated",
            "スキル錬成": "スキル錬成",
            "血红色警示": "血紅色警示",
            "自动标注日语假音": "自動標註日語假名",
            "批量备份": "批量備份",

        ],

        .english: [
                        "section.type.Intro": "Intro",
            "section.type.Verse": "Verse",
            "section.type.Pre-Chorus": "Pre-Chorus",
            "section.type.Chorus": "Chorus",
            "section.type.Post-Chorus": "Post-Chorus",
            "section.type.Bridge": "Bridge",
            "section.type.Hook": "Hook",
            "section.type.Refrain": "Refrain",
            "section.type.Interlude": "Interlude",
            "section.type.Solo": "Solo",
            "section.type.Outro": "Outro",
            "section.type.Coda": "Coda",
            "section.type.Custom": "Custom",
            "idea.type.Inspiration": "Inspiration",
            "idea.type.Setting": "Setting",
            "idea.type.Background": "Background",
            "idea.type.Note": "Note",
// ====== v1.5 新增 ======
            "笔记": "Notes",
            "译文": "Translation",
            "段落译文": "Section Translation",
            "更多": "More",
            "中文": "Chinese",
            "文件夹": "Folder",
            "新文件夹": "New Folder",
            "归并到文件夹": "Move to Folder",
            "重命名": "Rename",
            "解散文件夹": "Disband Folder",
            "备份文件夹": "Backup Folder",
            "导出文件夹": "Export Folder",
            "选中 %d 项": "%d selected",
            "已选中": "Selected",
            "取消选择": "Deselect",
            "选择歌曲": "Select Songs",
            "目标文件夹": "Target Folder",
            "新建文件夹": "Create Folder",
            "歌单": "Playlist",
            "歌曲类型": "Song Type",
            "回收站": "Trash",
            "移到回收站": "Move to Trash",
            "永久删除": "Delete Permanently",
            "将歌曲移到回收站": "Move song to Trash?",
            "将歌曲永久删除": "Delete song permanently? This cannot be undone!",
            "将文件夹永久删除": "Permanently delete folder and all songs inside? This cannot be undone!",
            "清空回收站": "Empty Trash",
            "在回收站中再次删除才能永久删除": "Delete again in Trash to remove permanently",
            "已选 %d 项": "%d selected",
            "已选 1 项": "1 selected",
            // ====== v1.6 节拍 / 文件夹操作 ======
            "节拍": "Beat",
            "节拍器": "Metronome",
            "停止": "Stop",
            "停止节拍器": "Stop metronome",
            "启动节拍器": "Start metronome",
            // ====== v1.7 歌词预览 / UI补充 ======
            "歌词预览": "Lyrics Preview",
            "预览歌词": "Preview Lyrics",
            "未命名歌曲": "Untitled",
            "未知艺术家": "Unknown Artist",
            "暂无歌词": "No lyrics yet",
            "双击跳转到段落": "Double-click to jump to section",
            "正在预览": "Previewing",
            "展开 / 收起元信息": "Show / Hide Metadata",

            "删除文件夹": "Delete Folder",
            "双击展开/折叠文件夹": "Double-click to expand/collapse",
            "确定要删除文件夹": "Delete this folder?",

            "备份曲目库（含文件夹结构）": "Backup library (with folders)",
            "导入文件夹": "Import Folder",
            // ====== v1.5.2 批量操作 ======
            "批量导出": "Batch Export",
            "批量移到回收站": "Move to Trash",
            "批量恢复": "Batch Restore",
            "批量永久删除": "Batch Delete Permanently",
            "批量移到根目录": "Move to Root",
            "移到根目录": "Move to Root",
            "移到其他文件夹": "Move to Other Folder",
            "批量移到其他文件夹": "Batch Move to Other Folder",
            "合并到新文件夹": "Merge to New Folder",
            "合并到文件夹": "Merge to Folder",
            "将 %d 首歌曲移到回收站？": "Move %d songs to Trash?",
            "导入 .smelody.txt 文件（可多选）": "Import .smelody.txt files (multiple)",
            "导入文件夹（不递归套娃，归到同名文件夹）": "Import folder (flat, to same-named folder)",
            "批量导入文件夹": "Batch Import Folder",
            "选择要导入的 .smelody.txt 文件（可多选）": "Select .smelody.txt files to import (multiple)",

            "导入备份文件夹（含套娃结构）": "Import backup folder (with nested structure)",
            "导入成功 (%d 首歌曲)": "Imported %d songs",
            "输入文件夹名": "Enter folder name",
            "输入新文件夹名": "Enter new folder name",
            "套娃文件夹": "Nested Folder",

"确定": "OK",
            "取消": "Cancel",
            "歌词导出": "Lyrics Export",
            "歌曲信息": "Song Info",
            "歌词": "Lyrics",
            "创建时间": "Created",
            "修改时间": "Modified",
            "导出时间": "Exported",
            "请先在歌曲语言中加入日语": "Please add Japanese to song languages first",
            "导出为文本文件（含全部信息）": "Export as Text File (with all info)",
            "将歌词的全部信息导出为文本文件": "Export all lyrics information to a text file",
            "导入歌曲": "Import Song",
            "导入歌曲文件": "Import Song File",
            "选择要导入的 .smelody.txt 文件": "Select .smelody.txt file to import",
            "导入成功": "Import Successful",
            "导入失败": "Import Failed",
            "数据管理": "Data Management",
            "一键备份曲目库": "One-Click Backup Library",
            "将所有歌曲按 .smelody.txt 格式打包到选定文件夹": "Package all songs as .smelody.txt to chosen folder",
            "备份": "Backup",
            "成功备份 %d 首歌曲到\n%@": "Successfully backed up %d songs to\n%@",
            "成功 %d 首，失败 %d 首": "%d succeeded, %d failed",
            "选择保存备份的文件夹": "Choose folder to save backup",
            "选择这里": "Choose",
            "删除前显示确认弹窗": "Show confirmation before delete",
            "删除歌曲、段落、灵感前提示确认（暂不可恢复）": "Confirm before deleting songs/sections/ideas (irreversible)",
            "确认删除": "Confirm Delete",
            "此操作暂不可恢复": "This action is irreversible",
            "不再提醒（可在设置中重新开启）": "Don't ask again (can re-enable in Settings)",
            "将删除歌曲": "Delete song",
            "将删除段落": "Delete section",
            "将删除条目": "Delete item",
            "将删除 %d 个段落": "Delete %d sections",
            "包含": "contains",
            "个段落": " sections",
            "条灵感与设定": " ideas and settings",
            "条译文": " translations",
            "帮助": "Help",
            "下载链接": "Download Link",
            "检查版本更新": "Check for Updates",
            "启动时检查更新": "Check on Launch",
            "启动时检查更新说明": "Silently check GitHub releases at launch; only alert when a newer version exists.",
            "发现新版本": "New version available",
            "前往下载": "Download",
            "稍后": "Later",
            "已是最新版本": "You're up to date",
            "检查更新失败": "Update check failed",
            "正在检查更新": "Checking for updates",
            "预览段落小字": "Section caption",
            "预览段落小字说明": "The small type under each preview section: notes or translation. Empty stays hidden.",
            "更新日志": "Changelog",
            "查看更新日志": "View Changelog",
            "查看每个版本的更新内容": "View changes for each version",
            "使用指南": "Usage Guide",
            "技能炼成": "Skill Integrated",
            "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用": "Export Simple Melody's lyric Skills to an AI Agent",
            "词炼成": "Lyric Forge",
            "曲炼成": "Music Forge",
            "导出 Skill 文件": "Export Skill File",
            "复制到剪贴板": "Copy to Clipboard",
            "Skill 简介": "Skill Overview",
            "smelody-lyric-create": "smelody-lyric-create",
            "smelody-music-create": "smelody-music-create",
            "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）": "Creative needs → complete .smelody.txt (importable to Simple Melody)",
            "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）": ".smelody.txt → music AI input (SUNO / Udio)",
            "保存为": "Save as",
            "保存成功": "Save successful",
            "保存失败": "Save failed",
            "：找不到 SKILL.md 资源": ": SKILL.md resource not found",
            "复制成功": "Copy successful",
            "复制失败": "Copy failed",
            "选择保存位置": "Choose save location",
            "Skill 文件（.md）": "Skill file (.md)",
            "Skill 文件夹父目录": "Parent folder for Skill directory",
            "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。": "Lyric Forge turns creative needs into importable .smelody.txt lyric files for Simple Melody.",
            "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。": "Music Forge distills .smelody.txt into a two-section file ready for music AI (SUNO / Udio, etc.).",
            "典型工作流": "Typical workflow",
            "完整工作流（推荐）": "Full workflow (recommended)",
            "第一步：做词炼成": "Step 1: Lyric Forge",
            "第二步：做曲炼成": "Step 2: Music Forge",
            "第三步：交给 AI Agent 作曲": "Step 3: Hand off to AI Agent",
            "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）": "Send creative needs to AI Agent (with SUNO/Udio tools)",
            "描述歌曲主题、风格、参考等": "Describe song theme, style, references, etc.",
            "触发词：": "Trigger words:",
            "触发词": "Trigger words",
            "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"": "\"Do lyric forge\" / \"Write lyrics in smelody format\" / \"Write a song in Simple Melody format\"",
            "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"": "\"Do music forge\" / \"Prepare SUNO prompt\" / \"Prepare lyrics for AI composition\"",
            "输出": "Output",
            "把完整歌词文件保存为 .smelody.txt": "Save complete lyric file as .smelody.txt",
            "在 Simple Melody 中导入": "Import in Simple Melody",
            "把 .smelody.txt 歌词文件发给 AI Agent": "Send .smelody.txt lyric file to AI Agent",
            "AI 提炼出两段式输出文件": "AI distills into a two-section output file",
            "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框": "Paste the upper lyric section to SUNO / Udio's Lyrics input",
            "下半部分作曲建议作为 Style prompt 的一部分": "Use the lower section as part of Style prompt",
            "如果您无法理解以上内容请不要使用该功能": "If you cannot understand the above, please do not use this feature",
            "Skill需要移交给有文件处理能力的LLM": "The Skill must be handed to an LLM that can handle files",
            "否则无效": "otherwise invalid",
            "复制 Skill 文本": "Copy Skill text",
            "已复制到剪贴板": "Copied to clipboard",
            "词炼成：AI 输出完整 .smelody.txt": "Lyric Forge: AI outputs complete .smelody.txt",
            "曲炼成：AI 输出两段式（歌词 + 作曲建议）": "Music Forge: AI outputs two-section file (lyrics + composition hints)",
            "软件介绍 + 各功能使用说明（随界面语言切换）": "App introduction + feature usage guide",
            "最新": "Latest",
            "版本": "Version",
            "开发者": "Developer",
            "平台": "Platform",
            "Apple Silicon 原生": "Apple Silicon Native",
            "保存": "Save",
            "删除": "Delete",
            "编辑": "Edit",
            "新建": "New",
            "搜索": "Search",
            "关闭": "Close",
            "复制": "Copy",
            "粘贴": "Paste",
            "导出": "Export",
            "导入": "Import",

            "曲目库": "Songs",
            "首": "songs",
            "条记录": " entries",
            "搜索曲目": "Search songs",
            "新建歌曲": "New Song",
            "新建第一首": "New First Song",
            "新建段落": "New Section",
            "还没有歌曲": "No songs yet",
            "没有匹配的歌曲": "No matching songs",
            "选择左侧的歌曲开始创作，或新建一首新歌。": "Pick a song on the left to start writing, or create a new one.",
            "Simple Melody": "Simple Melody",

            "排序方式": "Sort",
            "手动排序": "Manual",
            "最近修改": "Recently Modified",
            "标题": "Title",

            "段": " sections",
            "字": " chars",
            "BPM": "BPM",
            "Key": "Key",
            "未命名": "Untitled",

            "歌曲标题": "Song Title",
            "艺术家": "Artist",
            "语言": "Language",
            "调式": "Key",
            "标签（逗号分隔）": "Tags (comma-separated)",
            "收起": "Collapse",
            "展开": "Expand",
            "导出为文本文件": "Export as Text File",
            "复制全文到剪贴板": "Copy All to Clipboard",
            "段落笔记": "Section Notes",
            "段落类型": "Section Type",
            "自定义段落名": "Custom Section Name",
            "应用": "Apply",
            "如 Spoken Word": "e.g. Spoken Word",
            "上移": "Move Up",
            "下移": "Move Down",
            "复制段落": "Duplicate Section",
            "上": "Up",
            "下": "Down",

            "前奏": "Intro",
            "主歌": "Verse",
            "预副歌": "Pre-Chorus",
            "副歌": "Chorus",
            "副歌后": "Post-Chorus",
            "桥段": "Bridge",
            "记忆点": "Hook",
            "叠句": "Refrain",
            "间奏": "Interlude",
            "独奏": "Solo",
            "尾奏": "Outro",
            "终曲": "Coda",
            "自定义": "Custom",
            "添加段落": "Add Section",

            "正文": "Body",
            "读音摘要": "Pronunciation Preview",
            "注音列表": "Annotations",
            "添加读音": "Add Reading",
            "自动注音": "Auto Furigana",
            "对日语汉字自动生成假名注音": "Generate furigana for kanji automatically",
            "为指定位置的文字添加读音": "Add reading for text at specified position",
            "清除注音选项": "Clear annotations",
            "清除所有自动注音": "Clear All Auto Annotations",
            "清除所有手动注音": "Clear All Manual Annotations",
            "在正文中的位置": "Position in body",
            "起始: %d": "Start: %d",
            "长度: %d": "Length: %d",
            "原文预览": "Original Preview",
            "原文": "Original",
            "假名读音": "Furigana",
            "拼音": "Pinyin",
            "Phonetic": "Phonetic",
            "编辑读音": "Edit Reading",
            "自动标注日语假音": "Auto-annotate Japanese furigana",

            "灵感与设定": "Ideas & Settings",
            "灵感": "Inspiration",
            "设定": "Setting",
            "背景": "Background",
            "备注": "Note",
            "全部": "All",
            "记录灵感、背景故事、设定...": "Record inspiration, background, settings...",
            "还没有灵感或设定": "No ideas or settings yet",
            "在这里记录创作灵感、角色设定或背景故事。": "Record your creative inspiration, character settings or background story here.",
            "这些内容不会出现在歌词正文里。": "These won't appear in the lyrics body.",

            "设置": "Settings",
            "主题": "Theme",
            "字体大小": "Font size",
            "较小": "Smaller",
            "较大": "Larger",
            "跟随系统": "Follow System",
            "浅色": "Light",
            "深色": "Dark",
            "界面语言": "Interface Language",
            "接入大模型": "Connect a language model",
            "供以后的注音、翻译等功能使用": "For later features such as furigana and translation",
            "供应商网址": "Provider URL",
            "模型名": "Model name",
            "Imagine": "Imagine",
            "段落Imagine": "Section Imagine",
            "翻译": "Translation",
            "创意": "Creative",
            "注音": "Furigana",
            "即将推出": "Coming soon",
            "只修改这一段": "Only this section changes",
            "也可填写歌曲语言、速度、调式和节拍": "Can also fill the title, song language, tempo, key, and meter",
            "提示词可留空": "Prompt, optional",
            "目标语言": "Target language",
            "开始": "Start",
            "继续": "Continue",
            "依照当前格式": "Follow current format",
            "创意可能无法撤销或改错": "Creative changes may be irreversible",
            "创意会改动歌词，可能无法撤销或出现错误。确定要继续吗？": "Creative may change the lyrics in a way that cannot be undone or that is wrong. Continue?",
            "段落Imagine不能改整首歌或其他段落": "Section Imagine cannot change the whole song or other sections",
            "测试连接": "Test connection",
            "连接成功": "Connection succeeded",
            "连接失败": "Connection failed",
            "正在测试连接": "Testing connection",
            "请先填写供应商网址和 API Key": "Enter the provider URL and API key first",
            "回复格式无法识别，没有改动歌词": "The reply did not match the expected fields, so nothing was changed",
            "正在请模型处理": "Asking the model",
            "按 Command-Esc 取消": "Press Command-Esc to cancel",
            "没有歌词的段落不会翻译，笔记也不会被当成歌词": "Sections without lyrics are not translated, and notes are not treated as lyrics",
            "模型名可以留空": "The model name can be left empty",
            "建议选用参数量更大的模型，以便翻译、注音和创作更准确": "Prefer a large-parameter model for more accurate translation, furigana, and writing",
            "API Key": "API Key",
            "清除": "Clear",
            "首选语言": "Preferred Language",
            "歌曲语言（可多选）": "Song Languages (multiple)",

            "日语": "Japanese",
            "简体中文": "Simplified Chinese",
            "繁体中文": "Traditional Chinese",
            "英语": "English",
            "韩语": "Korean",
            "西班牙语": "Spanish",
            "法语": "French",
            "德语": "German",
            "意大利语": "Italian",
            "葡萄牙语": "Portuguese",
            "选择语言": "Select Languages",
            "已选": "Selected",
            "未选": "Unselected",
            "歌词语言": "Lyrics Language",
            "自动识别系统语言": "Auto-detect system language",
            "应用启动时检测系统语言": "Detect system language on launch",

            "Simple Melody 帮助": "Simple Melody Help",

            "暂无帮助文档，请查看 README.md": "No help document. See README.md",

            "关于 Simple Melody": "About Simple Melody",
            "v1.1 · Apple Silicon Native": "v1.1 · Apple Silicon Native",

            "灵感分栏": "Ideas Panel",
            "显示/隐藏灵感与设定分栏": "Show/hide ideas and settings panel",
            "专辑": "Album",
            "从 .smelody.txt 文件导入歌曲": "Import song from .smelody.txt file",
            "副本": "Copy",
            "备份曲目库": "Backup Library",
            "导出歌词": "Export Lyrics",
            "将删除注音": "Delete annotation",
            "将清除 %d 条手动注音": "Clear %d manual annotations",
            "将清除 %d 条自动注音": "Clear %d auto annotations",
            "将覆盖 %d 条现有的自动注音": "Will overwrite %d existing auto annotations",
            "展开元信息": "Show metadata",
            "展开元信息（语言/BPM/调式/标签）": "Show metadata (language/BPM/key/tags)",
            "折叠": "Collapse",
            "文件格式无效": "Invalid file format",
            "新歌曲": "New Song",
            "标签": "Tags",
            "缺少歌曲元信息": "Missing song metadata",
            "自动注音（仅日语段落）": "Auto Furigana (Japanese sections only)",
            "读取失败": "Read failed",
            "重新生成自动注音": "Regenerate Auto Furigana",
            "长按段落任意位置可拖动重排": "Long-press anywhere on a section to drag and reorder",
            "上移至顶部": "Move to Top",
            "下移至底部": "Move to Bottom",
            "段落拖动": "Section Drag",
            "段落拖动开关说明": "When on, press anywhere on a section to reorder: drop on the top half to insert before, bottom half to insert after; the list auto-scrolls up near the top edge. Swipe-to-delete is off while drag is on. The lyrics editor no longer inserts section ids as text.",
            "开启段落拖动功能？": "Enable Section Drag?",
            "我已知晓风险，继续开启": "Enable",
            "继续开启": "Enable",
            "拖动段落重排": "Drag sections to reorder",
            "key": "key",
            "技能煉成": "Skill Integrated",
            "Skill Integrated": "Skill Integrated",
            "スキル錬成": "Skill Integrated",
            "血红色警示": "Red warning",
            "自动标注日语假名": "Auto-annotate Japanese furigana",
            "批量备份": "Batch Backup",

        ],

        .japanese: [
                        "section.type.Intro": "イントロ",
            "section.type.Verse": "Aメロ",
            "section.type.Pre-Chorus": "Preコーラス",
            "section.type.Chorus": "サビ",
            "section.type.Post-Chorus": "Postコーラス",
            "section.type.Bridge": "ブリッジ",
            "section.type.Hook": "フック",
            "section.type.Refrain": "リフレイン",
            "section.type.Interlude": "間奏",
            "section.type.Solo": "ソロ",
            "section.type.Outro": "アウトロ",
            "section.type.Coda": "コーダ",
            "section.type.Custom": "カスタム",
            "idea.type.Inspiration": "インスピレーション",
            "idea.type.Setting": "設定",
            "idea.type.Background": "背景",
            "idea.type.Note": "メモ",
// ====== v1.5 新增 ======
            "笔记": "メモ",
            "译文": "訳文",
            "段落译文": "セクションの訳文",
            "更多": "その他",
            "中文": "中国語",
            "文件夹": "フォルダ",
            "新文件夹": "新規フォルダ",
            "归并到文件夹": "フォルダに移動",
            "重命名": "名前を変更",
            "解散文件夹": "フォルダを解散",
            "备份文件夹": "フォルダをバックアップ",
            "导出文件夹": "フォルダをエクスポート",
            "选中 %d 项": "%d 件選択中",
            "已选中": "選択済み",
            "取消选择": "選択解除",
            "选择歌曲": "楽曲を選択",
            "目标文件夹": "対象フォルダ",
            "新建文件夹": "フォルダを作成",
            "歌单": "プレイリスト",
            "歌曲类型": "楽曲タイプ",
            "回收站": "ゴミ箱",
            "移到回收站": "ゴミ箱へ移動",
            "永久删除": "完全に削除",
            "将歌曲移到回收站": "楽曲をゴミ箱へ移動しますか？",
            "将歌曲永久删除": "楽曲を完全に削除しますか？この操作は元に戻せません！",
            "将文件夹永久删除": "フォルダと内部の楽曲をすべて完全に削除しますか？この操作は元に戻せません！",
            "清空回收站": "ゴミ箱を空にする",
            "在回收站中再次删除才能永久删除": "完全に削除するにはゴミ箱でもう一度削除してください",
            "已选 %d 项": "%d 件選択中",
            "已选 1 项": "1 件選択中",
            // ====== v1.6 节拍 / 文件夹操作 ======
            "节拍": "拍子",
            "节拍器": "メトロノーム",
            "停止": "停止",
            "停止节拍器": "メトロノームを停止",
            "启动节拍器": "メトロノームを開始",
            // ====== v1.7 歌词预览 / UI补充 ======
            "歌词预览": "歌詞プレビュー",
            "预览歌词": "歌詞をプレビュー",
            "未命名歌曲": "無題の曲",
            "未知艺术家": "不明なアーティスト",
            "暂无歌词": "歌詞はまだありません",
            "双击跳转到段落": "ダブルクリックでセクションにジャンプ",
            "正在预览": "プレビュー中",
            "展开 / 收起元信息": "メタ情報を表示 / 非表示",

            "删除文件夹": "フォルダを削除",
            "双击展开/折叠文件夹": "ダブルクリックで展開/折りたたみ",
            "确定要删除文件夹": "フォルダを削除しますか？",

            "备份曲目库（含文件夹结构）": "ライブラリをバックアップ（フォルダ構造を含む）",
            "导入文件夹": "フォルダをインポート",
            // ====== v1.5.2 批量操作 ======
            "批量备份": "一括バックアップ",
            "批量导出": "一括エクスポート",
            "批量移到回收站": "ゴミ箱へ一括移動",
            "批量恢复": "一括復元",
            "批量永久删除": "一括完全削除",
            "批量移到根目录": "ルートへ一括移動",
            "移到根目录": "ルートに移動",
            "移到其他文件夹": "別のフォルダに移動",
            "批量移到其他文件夹": "一括で別のフォルダに移動",
            "合并到新文件夹": "新規フォルダにマージ",
            "合并到文件夹": "フォルダにマージ",
            "将 %d 首歌曲移到回收站？": "%d 曲をゴミ箱へ移動しますか？",
            "导入 .smelody.txt 文件（可多选）": ".smelody.txt ファイルをインポート（複数選択可）",
            "导入文件夹（不递归套娃，归到同名文件夹）": "フォルダをインポート（再帰なし、同名フォルダへ）",
            "批量导入文件夹": "一括フォルダインポート",
            "选择要导入的 .smelody.txt 文件（可多选）": "インポートする .smelody.txt ファイルを選択（複数可）",

            "导入备份文件夹（含套娃结构）": "バックアップフォルダをインポート（入れ子構造を含む）",
            "导入成功 (%d 首歌曲)": "%d 曲をインポートしました",
            "输入文件夹名": "フォルダ名を入力",
            "输入新文件夹名": "新しいフォルダ名を入力",
            "套娃文件夹": "入れ子フォルダ",

"确定": "OK",
            "取消": "キャンセル",
            "歌词导出": "歌詞エクスポート",
            "歌曲信息": "楽曲情報",
            "歌词": "歌詞",
            "创建时间": "作成日時",
            "修改时间": "更新日時",
            "导出时间": "エクスポート日時",
            "请先在歌曲语言中加入日语": "まず楽曲の言語に日本語を追加してください",
            "导出为文本文件（含全部信息）": "テキストファイルでエクスポート（全情報を含む）",
            "将歌词的全部信息导出为文本文件": "歌詞の全情報をテキストファイルにエクスポート",
            "导入歌曲": "曲をインポート",
            "导入歌曲文件": "曲ファイルをインポート",
            "选择要导入的 .smelody.txt 文件": "インポートする .smelody.txt ファイルを選択",
            "导入成功": "インポート成功",
            "导入失败": "インポート失敗",
            "数据管理": "データ管理",
            "一键备份曲目库": "楽曲ライブラリを一括バックアップ",
            "将所有歌曲按 .smelody.txt 格式打包到选定文件夹": "すべての曲を .smelody.txt で選択フォルダに書き出し",
            "备份": "バックアップ",
            "成功备份 %d 首歌曲到\n%@": "%d 曲をバックアップしました\n%@",
            "成功 %d 首，失败 %d 首": "%d 曲成功、%d 曲失敗",
            "选择保存备份的文件夹": "バックアップ保存フォルダを選択",
            "选择这里": "選択",
            "删除前显示确认弹窗": "削除前に確認ダイアログを表示",
            "删除歌曲、段落、灵感前提示确认（暂不可恢复）": "曲/セクション/アイデアの削除前に確認（復元不可）",
            "确认删除": "削除を確認",
            "此操作暂不可恢复": "この操作は復元できません",
            "不再提醒（可在设置中重新开启）": "次回から表示しない（設定で再有効化可能）",
            "将删除歌曲": "曲を削除",
            "将删除段落": "セクションを削除",
            "将删除条目": "項目を削除",
            "将删除 %d 个段落": "%d 個のセクションを削除",
            "包含": "含む",
            "个段落": " セクション",
            "条灵感与设定": " 件のアイデア・設定",
            "条译文": " 件の訳文",
            "帮助": "ヘルプ",
            "下载链接": "ダウンロードリンク",
            "检查版本更新": "更新を確認",
            "启动时检查更新": "起動時に更新確認",
            "启动时检查更新说明": "起動時に GitHub のリリースを黙って確認し、新しい版があるときだけ通知します。",
            "发现新版本": "新しいバージョンがあります",
            "前往下载": "ダウンロードへ",
            "稍后": "あとで",
            "已是最新版本": "最新です",
            "检查更新失败": "更新確認に失敗しました",
            "正在检查更新": "更新を確認しています",
            "预览段落小字": "セクションの小字",
            "预览段落小字说明": "プレビュー各セクション下の小字をメモ / 訳文で切り替え。空なら表示しません。",
            "更新日志": "更新履歴",
            "查看更新日志": "更新履歴を見る",
            "使用指南": "使い方ガイド",
            "技能炼成": "スキル錬成",
            "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用": "Simple Melody の歌詞 Skill を AI Agent にエクスポート",
            "词炼成": "詞錬成",
            "曲炼成": "曲錬成",
            "导出 Skill 文件": "Skill ファイルをエクスポート",
            "复制到剪贴板": "クリップボードにコピー",
            "Skill 简介": "Skill 概要",
            "smelody-lyric-create": "smelody-lyric-create",
            "smelody-music-create": "smelody-music-create",
            "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）": "創作ニーズ → 完全な .smelody.txt（Simple Melody にインポート可能）",
            "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）": ".smelody.txt → 作曲 AI 入力（SUNO / Udio）",
            "保存为": "名前を付けて保存",
            "保存成功": "保存成功",
            "保存失败": "保存失敗",
            "：找不到 SKILL.md 资源": "：SKILL.md リソースが見つかりません",
            "复制成功": "コピー成功",
            "复制失败": "コピー失敗",
            "选择保存位置": "保存場所を選択",
            "Skill 文件（.md）": "Skill ファイル（.md）",
            "Skill 文件夹父目录": "Skill フォルダの親ディレクトリ",
            "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。": "詞錬成は創作ニーズを Simple Melody にインポート可能な .smelody.txt 歌詞ファイルに変換します。",
            "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。": "曲錬成は .smelody.txt を作曲 AI（SUNO / Udio など）が直接使用できる二段組ファイルに提炼します。",
            "典型工作流": "典型的なワークフロー",
            "完整工作流（推荐）": "完全なワークフロー（推奨）",
            "第一步：做词炼成": "ステップ 1：詞錬成",
            "第二步：做曲炼成": "ステップ 2：曲錬成",
            "第三步：交给 AI Agent 作曲": "ステップ 3：AI Agent に作曲を任せる",
            "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）": "創作ニーズを AI Agent（SUNO/Udio ツール付き）に送信",
            "描述歌曲主题、风格、参考等": "曲のテーマ、スタイル、参考資料などを記述",
            "触发词：": "トリガーワード：",
            "触发词": "トリガーワード",
            "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"": "\"詞錬成を実行\" / \"smelody 形式で歌詞を書く\" / \"Simple Melody 形式の歌詞を書く\"",
            "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"": "\"曲錬成を実行\" / \"SUNO プロンプトを準備\" / \"AI 作曲用に歌詞を整理\"",
            "输出": "出力",
            "把完整歌词文件保存为 .smelody.txt": "完全な歌詞ファイルを .smelody.txt として保存",
            "在 Simple Melody 中导入": "Simple Melody でインポート",
            "把 .smelody.txt 歌词文件发给 AI Agent": ".smelody.txt 歌詞ファイルを AI Agent に送信",
            "AI 提炼出两段式输出文件": "AI が二段組出力ファイルに提炼",
            "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框": "上部の歌詞を SUNO / Udio の Lyrics 入力欄に貼り付け",
            "下半部分作曲建议作为 Style prompt 的一部分": "下部の作曲提案を Style prompt の一部として使用",
            "如果您无法理解以上内容请不要使用该功能": "上記の内容が理解できない場合は、この機能を使用しないでください",
            "Skill需要移交给有文件处理能力的LLM": "Skill はファイルを扱える LLM に引き渡す必要があります",
            "否则无效": "さもないと無効です",
            "复制 Skill 文本": "Skill テキストをコピー",
            "已复制到剪贴板": "クリップボードにコピーしました",
            "词炼成：AI 输出完整 .smelody.txt": "詞錬成：AI は完全な .smelody.txt を出力",
            "曲炼成：AI 输出两段式（歌词 + 作曲建议）": "曲錬成：AI は二段組ファイル（歌詞 + 作曲提案）を出力",
            "软件介绍 + 各功能使用说明（随界面语言切换）": "アプリ紹介 + 各機能の使い方ガイド",
            "查看每个版本的更新内容": "各バージョンの更新内容を見る",
            "最新": "最新",
            "版本": "バージョン",
            "开发者": "開発者",
            "平台": "プラットフォーム",
            "Apple Silicon 原生": "Apple Silicon ネイティブ",
            "保存": "保存",
            "删除": "削除",
            "编辑": "編集",
            "新建": "新規",
            "搜索": "検索",
            "关闭": "閉じる",
            "复制": "コピー",
            "粘贴": "貼り付け",
            "导出": "エクスポート",
            "导入": "インポート",

            "曲目库": "楽曲ライブラリ",
            "首": "曲",
            "条记录": "件",
            "搜索曲目": "楽曲を検索",
            "新建歌曲": "新しい曲",
            "新建第一首": "最初の曲を作る",
            "新建段落": "新しいセクション",
            "还没有歌曲": "曲がまだありません",
            "没有匹配的歌曲": "一致する曲がありません",
            "选择左侧的歌曲开始创作，或新建一首新歌。": "左側で曲を選ぶか、新しい曲を作成してください。",
            "Simple Melody": "Simple Melody",

            "排序方式": "並び替え",
            "手动排序": "手動",
            "最近修改": "最近更新",
            "标题": "タイトル",

            "段": "セクション",
            "字": "文字",
            "BPM": "BPM",
            "Key": "キー",
            "未命名": "無題",

            "歌曲标题": "曲のタイトル",
            "艺术家": "アーティスト",
            "语言": "言語",
            "调式": "キー",
            "标签（逗号分隔）": "タグ（カンマ区切り）",
            "收起": "折りたたむ",
            "展开": "展開",
            "导出为文本文件": "テキストファイルでエクスポート",
            "复制全文到剪贴板": "全文をクリップボードにコピー",
            "段落笔记": "セクションのメモ",
            "段落类型": "セクションタイプ",
            "自定义段落名": "カスタムセクション名",
            "应用": "適用",
            "如 Spoken Word": "例: Spoken Word",
            "上移": "上へ",
            "下移": "下へ",
            "复制段落": "セクションを複製",
            "上": "上",
            "下": "下",

            "前奏": "イントロ",
            "主歌": "Aメロ",
            "预副歌": "プレコーラス",
            "副歌": "サビ",
            "副歌后": "ポストコーラス",
            "桥段": "ブリッジ",
            "记忆点": "フック",
            "叠句": "リフレイン",
            "间奏": "間奏",
            "独奏": "ソロ",
            "尾奏": "アウトロ",
            "终曲": "コーダ",
            "自定义": "カスタム",
            "添加段落": "セクションを追加",

            "正文": "本文",
            "读音摘要": "ふりがなプレビュー",
            "注音列表": "ふりがなリスト",
            "添加读音": "ふりがなを追加",
            "自动注音": "自動ふりがな",
            "对日语汉字自动生成假名注音": "漢字に自動でふりがなを生成",
            "为指定位置的文字添加读音": "指定位置の文字にふりがなを追加",
            "清除注音选项": "ふりがなをクリア",
            "清除所有自动注音": "自動ふりがなを全て削除",
            "清除所有手动注音": "手動ふりがなを全て削除",
            "在正文中的位置": "本文中の位置",
            "起始: %d": "開始: %d",
            "长度: %d": "長さ: %d",
            "原文预览": "原文プレビュー",
            "原文": "原文",
            "假名读音": "ふりがな",
            "拼音": "拼音",
            "Phonetic": "Phonetic",
            "编辑读音": "ふりがなを編集",
            "自动标注日语假音": "日本語の漢字に自動でふりがなを付ける",

            "灵感与设定": "インスピレーション・設定",
            "灵感": "インスピレーション",
            "设定": "設定",
            "背景": "背景",
            "备注": "メモ",
            "全部": "すべて",
            "记录灵感、背景故事、设定...": "インスピレーション、背景、設定を記録...",
            "还没有灵感或设定": "インスピレーションや設定がまだありません",
            "在这里记录创作灵感、角色设定或背景故事。": "ここに創作のインスピレーションやキャラクター設定、背景を記録してください。",
            "这些内容不会出现在歌词正文里。": "これらは歌詞の本文には表示されません。",

            "设置": "設定",
            "主题": "テーマ",
            "字体大小": "フォントサイズ",
            "较小": "小さく",
            "较大": "大きく",
            "跟随系统": "システムに合わせる",
            "浅色": "ライト",
            "深色": "ダーク",
            "界面语言": "インターフェース言語",
            "接入大模型": "大規模言語モデルを接続",
            "供以后的注音、翻译等功能使用": "今後のふりがなや翻訳などの機能に使います",
            "供应商网址": "プロバイダの URL",
            "模型名": "モデル名",
            "Imagine": "Imagine",
            "段落Imagine": "段落 Imagine",
            "翻译": "翻訳",
            "创意": "創作",
            "注音": "ふりがな",
            "即将推出": "近日追加",
            "只修改这一段": "このセクションだけを変更します",
            "也可填写歌曲语言、速度、调式和节拍": "曲名、曲の言語、テンポ、調、拍子も記入できます",
            "提示词可留空": "追加の要望（空でもよい）",
            "目标语言": "翻訳先の言語",
            "开始": "開始",
            "继续": "続ける",
            "依照当前格式": "現在の形式に合わせる",
            "创意可能无法撤销或改错": "創作は取り消せないことがあります",
            "创意会改动歌词，可能无法撤销或出现错误。确定要继续吗？": "創作は歌詞を変え、取り消せなかったり誤ったりすることがあります。続けますか？",
            "段落Imagine不能改整首歌或其他段落": "段落 Imagine では曲全体や他のセクションは変えられません",
            "测试连接": "接続を試す",
            "连接成功": "接続できました",
            "连接失败": "接続できませんでした",
            "正在测试连接": "接続を試しています",
            "请先填写供应商网址和 API Key": "先にプロバイダの URL と API キーを入力してください",
            "回复格式无法识别，没有改动歌词": "返信の形式が合わないため、歌詞は変更していません",
            "正在请模型处理": "モデルに依頼しています",
            "按 Command-Esc 取消": "Command-Esc で中止",
            "没有歌词的段落不会翻译，笔记也不会被当成歌词": "歌詞が空のセクションは翻訳せず、メモは歌詞として扱いません",
            "模型名可以留空": "モデル名は空でも構いません",
            "建议选用参数量更大的模型，以便翻译、注音和创作更准确": "翻訳、ふりがな、創作をより正確にするには、パラメータの大きいモデルを選んでください",
            "API Key": "API Key",
            "清除": "消去",
            "首选语言": "優先言語",
            "歌曲语言（可多选）": "曲の言語（複数選択可）",

            "日语": "日本語",
            "简体中文": "簡体中国語",
            "繁体中文": "繁体中国語",
            "英语": "英語",
            "韩语": "韓国語",
            "西班牙语": "スペイン語",
            "法语": "フランス語",
            "德语": "ドイツ語",
            "意大利语": "イタリア語",
            "葡萄牙语": "ポルトガル語",
            "选择语言": "言語を選択",
            "已选": "選択済み",
            "未选": "未選択",
            "歌词语言": "歌詞の言語",
            "自动识别系统语言": "システム言語を自動検出",
            "应用启动时检测系统语言": "起動時にシステム言語を検出",

            "Simple Melody 帮助": "Simple Melody ヘルプ",

            "暂无帮助文档，请查看 README.md": "ヘルプドキュメントはありません。README.md を参照してください。",

            "关于 Simple Melody": "Simple Melody について",
            "v1.1 · Apple Silicon Native": "v1.1 · Apple Silicon Native",

            "灵感分栏": "アイデアパネル",
            "显示/隐藏灵感与设定分栏": "アイデア・設定パネルの表示/非表示",
            "专辑": "アルバム",
            "从 .smelody.txt 文件导入歌曲": ".smelody.txt ファイルから曲をインポート",
            "副本": "コピー",
            "备份曲目库": "ライブラリをバックアップ",
            "导出歌词": "歌詞をエクスポート",
            "将删除注音": "ふりがなを削除",
            "将清除 %d 条手动注音": "手動ふりがな %d 件を削除",
            "将清除 %d 条自动注音": "自動ふりがな %d 件を削除",
            "将覆盖 %d 条现有的自动注音": "既存の自動ふりがな %d 件を上書きします",
            "展开元信息": "メタデータを展開",
            "展开元信息（语言/BPM/调式/标签）": "メタデータを展開（言語/BPM/キー/タグ）",
            "折叠": "折りたたむ",
            "文件格式无效": "ファイル形式が無効",
            "新歌曲": "新しい曲",
            "标签": "タグ",
            "缺少歌曲元信息": "楽曲のメタデータが不足",
            "自动注音（仅日语段落）": "自動ふりがな（日本語セクションのみ）",
            "读取失败": "読み込み失敗",
            "重新生成自动注音": "自動ふりがなを再生成",
            "长按段落任意位置可拖动重排": "セクションの任意の場所を長押しでドラッグ並び替え",
            "上移至顶部": "一番上に移動",
            "下移至底部": "一番下に移動",
            "段落拖动": "セクションドラッグ",
            "段落拖动开关说明": "有効化するとセクションの任意の位置を長押しして並べ替えできます。上半分にドロップするとその前へ、下半分だとその後へ挿入。リスト上部付近では自動で上スクロールします。有効中はスワイプ削除はオフ。歌詞エディタにセクション ID がテキストとして入ることはありません。",
            "开启段落拖动功能？": "セクションドラッグを有効にしますか？",
            "我已知晓风险，继续开启": "有効にする",
            "继续开启": "有効にする",
            "拖动段落重排": "セクションをドラッグして並べ替え",
            "key": "key",
            "技能煉成": "スキル錬成",
            "Skill Integrated": "スキル錬成",
            "スキル錬成": "スキル錬成",
            "血红色警示": "赤い警告",
            "自动标注日语假名": "日本語の漢字に自動でふりがなを付ける",

        ],
        .korean: [
            "key": "키",
            "专辑": "앨범",
            "从 .smelody.txt 文件导入歌曲": ".smelody.txt 파일에서 곡 가져오기",
            "副本": "사본",
            "备份曲目库": "라이브러리 백업",
            "导出歌词": "가사 내보내기",
            "将删除注音": "주석을 삭제합니다",
            "将清除 %d 条手动注音": "수동 주석 %d개를 지웁니다",
            "将清除 %d 条自动注音": "자동 주석 %d개를 지웁니다",
            "将覆盖 %d 条现有的自动注音": "기존 자동 주석 %d개를 덮어씁니다",
            "展开元信息": "메타데이터 펼치기",
            "展开元信息（语言/BPM/调式/标签）": "메타데이터 펼치기(언어/BPM/조성/태그)",
            "折叠": "접기",
            "文件格式无效": "파일 형식이 잘못되었습니다",
            "新歌曲": "새 곡",
            "标签": "태그",
            "缺少歌曲元信息": "곡 메타데이터가 없습니다",
            "自动注音（仅日语段落）": "자동 후리가나(일본어 섹션만)",
            "读取失败": "읽기 실패",
            "重新生成自动注音": "자동 후리가나 다시 생성",
            "长按段落任意位置可拖动重排": "섹션의 아무 곳이나 길게 눌러 순서를 바꿉니다",
            "上移至顶部": "맨 위로",
            "下移至底部": "맨 아래로",
            "段落拖动": "섹션 드래그",
            "段落拖动开关说明": "켜면 섹션의 아무 곳이나 눌러 순서를 바꿀 수 있습니다. 위쪽 절반에 놓으면 앞에, 아래쪽 절반에 놓으면 뒤에 삽입됩니다. 목록 위쪽에 가까우면 자동으로 위로 스크롤됩니다. 켜져 있는 동안 스와이프 삭제는 꺼집니다. 가사 편집기에 섹션 번호가 텍스트로 들어가지 않습니다.",
            "开启段落拖动功能？": "섹션 드래그를 켤까요?",
            "我已知晓风险，继续开启": "켜기",
            "继续开启": "켜기",
            "拖动段落重排": "드래그하여 섹션 정렬",
            "section.type.Intro": "인트로",
            "section.type.Verse": "벌스",
            "section.type.Pre-Chorus": "프리코러스",
            "section.type.Chorus": "코러스",
            "section.type.Post-Chorus": "포스트코러스",
            "section.type.Bridge": "브리지",
            "section.type.Hook": "훅",
            "section.type.Refrain": "리프레인",
            "section.type.Interlude": "간주",
            "section.type.Solo": "솔로",
            "section.type.Outro": "아웃트로",
            "section.type.Coda": "코다",
            "section.type.Custom": "사용자 지정",
            "idea.type.Inspiration": "영감",
            "idea.type.Setting": "설정",
            "idea.type.Background": "배경",
            "idea.type.Note": "메모",
            "笔记": "메모",
            "译文": "번역",
            "段落译文": "섹션 번역",
            "更多": "더보기",
            "中文": "중국어",
            "文件夹": "폴더",
            "新文件夹": "새 폴더",
            "归并到文件夹": "폴더로 이동",
            "重命名": "이름 바꾸기",
            "解散文件夹": "폴더 해제",
            "备份文件夹": "폴더 백업",
            "导出文件夹": "폴더 내보내기",
            "选中 %d 项": "%d개 선택됨",
            "已选中": "선택됨",
            "取消选择": "선택 해제",
            "选择歌曲": "곡 선택",
            "目标文件夹": "대상 폴더",
            "新建文件夹": "폴더 만들기",
            "歌单": "재생목록",
            "歌曲类型": "곡 유형",
            "回收站": "휴지통",
            "移到回收站": "휴지통으로 이동",
            "永久删除": "영구 삭제",
            "将歌曲移到回收站": "곡을 휴지통으로 옮길까요?",
            "将歌曲永久删除": "곡을 영구 삭제할까요? 되돌릴 수 없습니다!",
            "将文件夹永久删除": "폴더와 안의 모든 곡을 영구 삭제할까요? 되돌릴 수 없습니다!",
            "清空回收站": "휴지통 비우기",
            "在回收站中再次删除才能永久删除": "영구 삭제하려면 휴지통에서 한 번 더 삭제하세요",
            "已选 %d 项": "%d개 선택됨",
            "已选 1 项": "1개 선택됨",
            "节拍": "박자",
            "节拍器": "메트로놈",
            "停止": "정지",
            "停止节拍器": "메트로놈 정지",
            "启动节拍器": "메트로놈 시작",
            "歌词预览": "가사 미리보기",
            "预览歌词": "가사 미리보기",
            "未命名歌曲": "제목 없는 곡",
            "未知艺术家": "알 수 없는 아티스트",
            "暂无歌词": "가사가 없습니다",
            "双击跳转到段落": "두 번 클릭하면 해당 섹션으로 이동합니다",
            "正在预览": "미리보는 중",
            "展开 / 收起元信息": "메타데이터 표시 / 숨기기",
            "删除文件夹": "폴더 삭제",
            "双击展开/折叠文件夹": "두 번 클릭하여 폴더를 펼치거나 접습니다",
            "确定要删除文件夹": "이 폴더를 삭제할까요?",
            "备份曲目库（含文件夹结构）": "라이브러리 백업(폴더 구조 포함)",
            "批量导出": "일괄 내보내기",
            "批量移到回收站": "휴지통으로 일괄 이동",
            "批量恢复": "일괄 복원",
            "批量永久删除": "일괄 영구 삭제",
            "批量移到根目录": "루트로 일괄 이동",
            "移到根目录": "루트로 이동",
            "移到其他文件夹": "다른 폴더로 이동",
            "批量移到其他文件夹": "다른 폴더로 일괄 이동",
            "合并到新文件夹": "새 폴더로 합치기",
            "合并到文件夹": "폴더로 합치기",
            "将 %d 首歌曲移到回收站？": "곡 %d개를 휴지통으로 옮길까요?",
            "导入 .smelody.txt 文件（可多选）": ".smelody.txt 파일 가져오기(여러 개 선택)",
            "导入文件夹（不递归套娃，归到同名文件夹）": "폴더 가져오기(중첩 없음, 같은 이름 폴더로)",
            "批量导入文件夹": "폴더 일괄 가져오기",
            "选择要导入的 .smelody.txt 文件（可多选）": "가져올 .smelody.txt 파일 선택(여러 개)",
            "导入文件夹": "폴더 가져오기",
            "导入备份文件夹（含套娃结构）": "백업 폴더 가져오기(중첩 구조 포함)",
            "导入成功 (%d 首歌曲)": "곡 %d개를 가져왔습니다",
            "输入文件夹名": "폴더 이름 입력",
            "输入新文件夹名": "새 폴더 이름 입력",
            "套娃文件夹": "중첩 폴더",
            "确定": "확인",
            "取消": "취소",
            "歌词导出": "가사 내보내기",
            "歌曲信息": "곡 정보",
            "歌词": "가사",
            "创建时间": "만든 시간",
            "修改时间": "수정 시간",
            "导出时间": "내보낸 시간",
            "请先在歌曲语言中加入日语": "먼저 곡 언어에 일본어를 추가하세요",
            "导出为文本文件（含全部信息）": "텍스트 파일로 내보내기(모든 정보 포함)",
            "将歌词的全部信息导出为文本文件": "가사의 모든 정보를 텍스트 파일로 내보냅니다",
            "导入歌曲": "곡 가져오기",
            "导入歌曲文件": "곡 파일 가져오기",
            "选择要导入的 .smelody.txt 文件": "가져올 .smelody.txt 파일 선택",
            "导入成功": "가져오기 성공",
            "导入失败": "가져오기 실패",
            "数据管理": "데이터 관리",
            "一键备份曲目库": "라이브러리 한 번에 백업",
            "将所有歌曲按 .smelody.txt 格式打包到选定文件夹": "모든 곡을 .smelody.txt로 선택한 폴더에 저장",
            "备份": "백업",
            "成功备份 %d 首歌曲到\n%@": "곡 %d개를 백업했습니다\n%@",
            "成功 %d 首，失败 %d 首": "성공 %d곡, 실패 %d곡",
            "选择保存备份的文件夹": "백업을 저장할 폴더 선택",
            "选择这里": "선택",
            "删除前显示确认弹窗": "삭제 전에 확인 창 표시",
            "删除歌曲、段落、灵感前提示确认（暂不可恢复）": "곡, 섹션, 아이디어를 삭제하기 전에 확인합니다(되돌릴 수 없음)",
            "确认删除": "삭제 확인",
            "此操作暂不可恢复": "이 작업은 되돌릴 수 없습니다",
            "不再提醒（可在设置中重新开启）": "다시 묻지 않기(설정에서 다시 켤 수 있음)",
            "将删除歌曲": "곡을 삭제합니다",
            "将删除段落": "섹션을 삭제합니다",
            "将删除条目": "항목을 삭제합니다",
            "将删除 %d 个段落": "섹션 %d개를 삭제합니다",
            "包含": "포함",
            "个段落": "개 섹션",
            "条灵感与设定": "개의 아이디어와 설정",
            "条译文": "개의 번역",
            "帮助": "도움말",
            "下载链接": "다운로드 링크",
            "检查版本更新": "업데이트 확인",
            "启动时检查更新": "시작할 때 업데이트 확인",
            "启动时检查更新说明": "시작할 때 GitHub 릴리스를 조용히 확인하고, 새 버전이 있을 때만 알립니다.",
            "发现新版本": "새 버전이 있습니다",
            "前往下载": "다운로드로 이동",
            "稍后": "나중에",
            "已是最新版本": "최신 버전입니다",
            "检查更新失败": "업데이트 확인에 실패했습니다",
            "正在检查更新": "업데이트를 확인하는 중",
            "预览段落小字": "섹션 아래 작은 글",
            "预览段落小字说明": "가사 미리보기에서 각 섹션 본문 아래의 작은 글입니다. 메모와 번역 중 고를 수 있으며, 비어 있으면 숨깁니다.",
            "更新日志": "업데이트 기록",
            "查看更新日志": "업데이트 기록 보기",
            "查看每个版本的更新内容": "버전별 변경 내용 보기",
            "最新": "최신",
            "使用指南": "사용 안내",
            "软件介绍 + 各功能使用说明（随界面语言切换）": "앱 소개와 기능 사용 안내",
            "技能炼成": "스킬 연마",
            "技能煉成": "스킬 연마",
            "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用": "Simple Melody의 가사 Skill을 AI 에이전트에 내보냅니다",
            "Skill Integrated": "Skill Integrated",
            "スキル錬成": "스킬 연마",
            "词炼成": "가사 연마",
            "曲炼成": "작곡 연마",
            "导出 Skill 文件": "Skill 파일 내보내기",
            "复制到剪贴板": "클립보드에 복사",
            "Skill 简介": "Skill 개요",
            "smelody-lyric-create": "smelody-lyric-create",
            "smelody-music-create": "smelody-music-create",
            "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）": "창작 요구 → 완전한 .smelody.txt(Simple Melody로 가져올 수 있음)",
            "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）": ".smelody.txt → 작곡 AI 입력(SUNO / Udio)",
            "保存为": "다른 이름으로 저장",
            "保存": "저장",
            "保存成功": "저장했습니다",
            "保存失败": "저장하지 못했습니다",
            "：找不到 SKILL.md 资源": ": SKILL.md 리소스를 찾을 수 없습니다",
            "复制成功": "복사했습니다",
            "复制失败": "복사하지 못했습니다",
            "选择保存位置": "저장 위치 선택",
            "Skill 文件（.md）": "Skill 파일(.md)",
            "Skill 文件夹父目录": "Skill 폴더의 상위 폴더",
            "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。": "가사 연마는 창작 요구를 Simple Melody로 가져올 수 있는 .smelody.txt 가사 파일로 바꿉니다.",
            "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。": "작곡 연마는 .smelody.txt를 작곡 AI(SUNO / Udio 등)가 바로 쓸 수 있는 두 부분 파일로 정리합니다.",
            "典型工作流": "일반적인 작업 흐름",
            "完整工作流（推荐）": "전체 작업 흐름(권장)",
            "第一步：做词炼成": "1단계: 가사 연마",
            "第二步：做曲炼成": "2단계: 작곡 연마",
            "第三步：交给 AI Agent 作曲": "3단계: AI 에이전트에게 작곡 맡기기",
            "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）": "창작 요구를 AI 에이전트(SUNO/Udio 도구가 있을 때)에 보냅니다",
            "描述歌曲主题、风格、参考等": "곡의 주제, 스타일, 참고 자료를 적습니다",
            "触发词：": "트리거 단어:",
            "触发词": "트리거 단어",
            "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"": "\"가사 연마\" / \"smelody 형식으로 가사 쓰기\" / \"Simple Melody 형식의 가사 쓰기\"",
            "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"": "\"작곡 연마\" / \"SUNO 프롬프트 준비\" / \"AI 작곡용으로 가사 정리\"",
            "输出": "출력",
            "把完整歌词文件保存为 .smelody.txt": "완성된 가사 파일을 .smelody.txt로 저장",
            "在 Simple Melody 中导入": "Simple Melody에서 가져오기",
            "把 .smelody.txt 歌词文件发给 AI Agent": ".smelody.txt 가사 파일을 AI 에이전트에 보냅니다",
            "AI 提炼出两段式输出文件": "AI가 두 부분으로 된 출력 파일을 만듭니다",
            "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框": "위쪽 가사를 SUNO / Udio의 Lyrics 입력란에 붙여 넣습니다",
            "下半部分作曲建议作为 Style prompt 的一部分": "아래쪽 작곡 제안을 Style prompt의 일부로 사용합니다",
            "如果您无法理解以上内容请不要使用该功能": "위의 내용을 이해할 수 없으면 이 기능을 사용하지 마세요",
            "Skill需要移交给有文件处理能力的LLM": "Skill은 파일을 처리할 수 있는 LLM에게 넘겨야 합니다",
            "否则无效": "그렇지 않으면 효과가 없습니다",
            "血红色警示": "빨간 경고",
            "复制 Skill 文本": "Skill 텍스트 복사",
            "已复制到剪贴板": "클립보드에 복사했습니다",
            "词炼成：AI 输出完整 .smelody.txt": "가사 연마: AI가 완전한 .smelody.txt를 출력",
            "曲炼成：AI 输出两段式（歌词 + 作曲建议）": "작곡 연마: AI가 두 부분(가사 + 작곡 제안)을 출력",
            "删除": "삭제",
            "编辑": "편집",
            "新建": "새로 만들기",
            "搜索": "검색",
            "关闭": "닫기",
            "复制": "복사",
            "粘贴": "붙여넣기",
            "导出": "내보내기",
            "导入": "가져오기",
            "曲目库": "곡 목록",
            "首": "곡",
            "条记录": "개 기록",
            "搜索曲目": "곡 검색",
            "新建歌曲": "새 곡",
            "新建第一首": "첫 곡 만들기",
            "新建段落": "새 섹션",
            "还没有歌曲": "곡이 없습니다",
            "没有匹配的歌曲": "일치하는 곡이 없습니다",
            "选择左侧的歌曲开始创作，或新建一首新歌。": "왼쪽에서 곡을 고르거나 새 곡을 만드세요.",
            "Simple Melody": "Simple Melody",
            "排序方式": "정렬",
            "手动排序": "수동",
            "最近修改": "최근 수정",
            "标题": "제목",
            "段": "개 섹션",
            "字": "자",
            "BPM": "BPM",
            "Key": "Key",
            "未命名": "제목 없음",
            "歌曲标题": "곡 제목",
            "艺术家": "아티스트",
            "语言": "언어",
            "调式": "조성",
            "标签（逗号分隔）": "태그(쉼표로 구분)",
            "收起": "접기",
            "展开": "펼치기",
            "导出为文本文件": "텍스트 파일로 내보내기",
            "复制全文到剪贴板": "전문을 클립보드에 복사",
            "段落笔记": "섹션 메모",
            "段落类型": "섹션 유형",
            "自定义段落名": "사용자 지정 섹션 이름",
            "应用": "적용",
            "如 Spoken Word": "예: Spoken Word",
            "上移": "위로",
            "下移": "아래로",
            "复制段落": "섹션 복제",
            "上": "위",
            "下": "아래",
            "前奏": "인트로",
            "主歌": "벌스",
            "预副歌": "프리코러스",
            "副歌": "코러스",
            "副歌后": "포스트코러스",
            "桥段": "브리지",
            "记忆点": "훅",
            "叠句": "리프레인",
            "间奏": "간주",
            "独奏": "솔로",
            "尾奏": "아웃트로",
            "终曲": "코다",
            "自定义": "사용자 지정",
            "添加段落": "섹션 추가",
            "正文": "본문",
            "读音摘要": "발음 미리보기",
            "注音列表": "주석 목록",
            "添加读音": "읽기 추가",
            "自动注音": "자동 후리가나",
            "对日语汉字自动生成假名注音": "일본어 한자에 후리가나를 자동으로 만듭니다",
            "为指定位置的文字添加读音": "지정한 위치의 글자에 읽기를 추가합니다",
            "清除注音选项": "주석 지우기 옵션",
            "清除所有自动注音": "자동 주석 모두 지우기",
            "清除所有手动注音": "수동 주석 모두 지우기",
            "在正文中的位置": "본문에서의 위치",
            "起始: %d": "시작: %d",
            "长度: %d": "길이: %d",
            "原文预览": "원문 미리보기",
            "原文": "원문",
            "假名读音": "후리가나",
            "拼音": "병음",
            "Phonetic": "Phonetic",
            "编辑读音": "읽기 편집",
            "自动标注日语假名": "일본어 한자에 후리가나 자동 표기",
            "灵感与设定": "아이디어와 설정",
            "灵感": "영감",
            "设定": "설정",
            "背景": "배경",
            "备注": "메모",
            "全部": "전체",
            "记录灵感、背景故事、设定...": "영감, 배경, 설정을 기록...",
            "还没有灵感或设定": "아이디어나 설정이 없습니다",
            "在这里记录创作灵感、角色设定或背景故事。": "여기에 창작 영감, 인물 설정, 배경 이야기를 적으세요.",
            "这些内容不会出现在歌词正文里。": "이 내용은 가사 본문에 나오지 않습니다.",
            "设置": "설정",
            "主题": "테마",
            "字体大小": "글자 크기",
            "较小": "작게",
            "较大": "크게",
            "跟随系统": "시스템을 따름",
            "浅色": "밝게",
            "深色": "어둡게",
            "界面语言": "인터페이스 언어",
            "接入大模型": "대형 언어 모델 연결",
            "供以后的注音、翻译等功能使用": "이후 후리가나, 번역 등의 기능에 사용합니다",
            "供应商网址": "공급자 주소",
            "模型名": "모델 이름",
            "Imagine": "Imagine",
            "段落Imagine": "단락 Imagine",
            "翻译": "번역",
            "创意": "창작",
            "注音": "후리가나",
            "即将推出": "곧 제공",
            "只修改这一段": "이 섹션만 바꿉니다",
            "也可填写歌曲语言、速度、调式和节拍": "제목, 곡의 언어, 빠르기, 조성, 박자도 채울 수 있습니다",
            "提示词可留空": "추가 요청 (비워 둘 수 있음)",
            "目标语言": "번역할 언어",
            "开始": "시작",
            "继续": "계속",
            "依照当前格式": "현재 형식을 따름",
            "创意可能无法撤销或改错": "창작은 되돌릴 수 없을 수 있습니다",
            "创意会改动歌词，可能无法撤销或出现错误。确定要继续吗？": "창작은 가사를 바꾸며 되돌릴 수 없거나 잘못될 수 있습니다. 계속할까요?",
            "段落Imagine不能改整首歌或其他段落": "단락 Imagine으로는 곡 전체나 다른 섹션을 바꿀 수 없습니다",
            "测试连接": "연결 테스트",
            "连接成功": "연결되었습니다",
            "连接失败": "연결하지 못했습니다",
            "正在测试连接": "연결을 테스트하는 중",
            "请先填写供应商网址和 API Key": "공급자 주소와 API 키를 먼저 입력하세요",
            "回复格式无法识别，没有改动歌词": "답변 형식이 맞지 않아 가사를 바꾸지 않았습니다",
            "正在请模型处理": "모델에 요청하는 중",
            "按 Command-Esc 取消": "Command-Esc로 취소",
            "没有歌词的段落不会翻译，笔记也不会被当成歌词": "가사가 없는 섹션은 번역하지 않고, 메모는 가사로 다루지 않습니다",
            "模型名可以留空": "모델 이름은 비워 둘 수 있습니다",
            "建议选用参数量更大的模型，以便翻译、注音和创作更准确": "번역, 후리가나, 창작을 더 정확하게 하려면 매개변수가 큰 모델을 고르세요",
            "API Key": "API Key",
            "清除": "지우기",
            "首选语言": "기본 언어",
            "歌曲语言（可多选）": "곡 언어(여러 개 선택)",
            "日语": "일본어",
            "简体中文": "중국어 간체",
            "繁体中文": "중국어 번체",
            "英语": "영어",
            "韩语": "한국어",
            "西班牙语": "스페인어",
            "法语": "프랑스어",
            "德语": "독일어",
            "意大利语": "이탈리아어",
            "葡萄牙语": "포르투갈어",
            "选择语言": "언어 선택",
            "已选": "선택됨",
            "未选": "선택 안 함",
            "歌词语言": "가사 언어",
            "自动识别系统语言": "시스템 언어 자동 인식",
            "应用启动时检测系统语言": "시작할 때 시스템 언어를 감지",
            "Simple Melody 帮助": "Simple Melody 도움말",
            "暂无帮助文档，请查看 README.md": "도움말 문서가 없습니다. README.md를 보세요.",
            "关于 Simple Melody": "Simple Melody 정보",
            "版本": "버전",
            "v1.1 · Apple Silicon Native": "v1.1 · Apple Silicon 네이티브",
            "灵感分栏": "아이디어 패널",
            "显示/隐藏灵感与设定分栏": "아이디어·설정 패널 표시/숨기기",
            "Apple Silicon 原生": "Apple Silicon 네이티브",
            "平台": "플랫폼",
            "开发者": "개발자",
            "自动标注日语假音": "일본어 한자에 후리가나 자동 표기",
            "批量备份": "일괄 백업",
        ],
        .spanish: [
            "key": "clave",
            "专辑": "Álbum",
            "从 .smelody.txt 文件导入歌曲": "Importar canción desde un archivo .smelody.txt",
            "副本": "Copia",
            "备份曲目库": "Copia de seguridad de la biblioteca",
            "导出歌词": "Exportar letra",
            "将删除注音": "Se eliminará la anotación",
            "将清除 %d 条手动注音": "Se borrarán %d anotaciones manuales",
            "将清除 %d 条自动注音": "Se borrarán %d anotaciones automáticas",
            "将覆盖 %d 条现有的自动注音": "Se sobrescribirán %d anotaciones automáticas",
            "展开元信息": "Mostrar metadatos",
            "展开元信息（语言/BPM/调式/标签）": "Mostrar metadatos (idioma/BPM/tono/etiquetas)",
            "折叠": "Plegar",
            "文件格式无效": "Formato de archivo no válido",
            "新歌曲": "Canción nueva",
            "标签": "Etiquetas",
            "缺少歌曲元信息": "Faltan los metadatos de la canción",
            "自动注音（仅日语段落）": "Furigana automático (solo secciones en japonés)",
            "读取失败": "Error de lectura",
            "重新生成自动注音": "Regenerar furigana automático",
            "长按段落任意位置可拖动重排": "Mantén pulsado cualquier punto de la sección para reordenar",
            "上移至顶部": "Mover al inicio",
            "下移至底部": "Mover al final",
            "段落拖动": "Arrastrar secciones",
            "段落拖动开关说明": "Al activarlo puedes reordenar pulsando cualquier punto de la sección: soltar en la mitad superior inserta antes y en la inferior después. Cerca del borde superior la lista se desplaza sola. El borrado por deslizamiento se desactiva. El editor ya no inserta el id de la sección como texto.",
            "开启段落拖动功能？": "¿Activar arrastre de secciones?",
            "我已知晓风险，继续开启": "Activar",
            "继续开启": "Activar",
            "拖动段落重排": "Arrastrar para reordenar secciones",
            "section.type.Intro": "Introducción",
            "section.type.Verse": "Estrofa",
            "section.type.Pre-Chorus": "Pre-estribillo",
            "section.type.Chorus": "Estribillo",
            "section.type.Post-Chorus": "Post-estribillo",
            "section.type.Bridge": "Puente",
            "section.type.Hook": "Gancho",
            "section.type.Refrain": "Estribillo repetido",
            "section.type.Interlude": "Interludio",
            "section.type.Solo": "Solo",
            "section.type.Outro": "Cierre",
            "section.type.Coda": "Coda",
            "section.type.Custom": "Personalizado",
            "idea.type.Inspiration": "Inspiración",
            "idea.type.Setting": "Ambientación",
            "idea.type.Background": "Trasfondo",
            "idea.type.Note": "Nota",
            "笔记": "Notas",
            "译文": "Traducción",
            "段落译文": "Traducción de la sección",
            "更多": "Más",
            "中文": "Chino",
            "文件夹": "Carpeta",
            "新文件夹": "Carpeta nueva",
            "归并到文件夹": "Mover a carpeta",
            "重命名": "Renombrar",
            "解散文件夹": "Disolver carpeta",
            "备份文件夹": "Copia de la carpeta",
            "导出文件夹": "Exportar carpeta",
            "选中 %d 项": "%d seleccionados",
            "已选中": "Seleccionado",
            "取消选择": "Deseleccionar",
            "选择歌曲": "Seleccionar canciones",
            "目标文件夹": "Carpeta de destino",
            "新建文件夹": "Crear carpeta",
            "歌单": "Lista",
            "歌曲类型": "Tipo de canción",
            "回收站": "Papelera",
            "移到回收站": "Mover a la papelera",
            "永久删除": "Eliminar permanentemente",
            "将歌曲移到回收站": "¿Mover la canción a la papelera?",
            "将歌曲永久删除": "¿Eliminar la canción permanentemente? No se puede deshacer.",
            "将文件夹永久删除": "¿Eliminar la carpeta y todas sus canciones? No se puede deshacer.",
            "清空回收站": "Vaciar papelera",
            "在回收站中再次删除才能永久删除": "Vuelve a eliminarla en la papelera para borrarla del todo",
            "已选 %d 项": "%d seleccionados",
            "已选 1 项": "1 seleccionado",
            "节拍": "Compás",
            "节拍器": "Metrónomo",
            "停止": "Detener",
            "停止节拍器": "Detener metrónomo",
            "启动节拍器": "Iniciar metrónomo",
            "歌词预览": "Vista previa de la letra",
            "预览歌词": "Previsualizar letra",
            "未命名歌曲": "Canción sin título",
            "未知艺术家": "Artista desconocido",
            "暂无歌词": "Aún no hay letra",
            "双击跳转到段落": "Doble clic para ir a la sección",
            "正在预览": "Previsualizando",
            "展开 / 收起元信息": "Mostrar / ocultar metadatos",
            "删除文件夹": "Eliminar carpeta",
            "双击展开/折叠文件夹": "Doble clic para expandir o plegar la carpeta",
            "确定要删除文件夹": "¿Eliminar esta carpeta?",
            "备份曲目库（含文件夹结构）": "Copia de la biblioteca (con carpetas)",
            "批量导出": "Exportación por lotes",
            "批量移到回收站": "Mover a la papelera por lotes",
            "批量恢复": "Restaurar por lotes",
            "批量永久删除": "Eliminar permanentemente por lotes",
            "批量移到根目录": "Mover a la raíz por lotes",
            "移到根目录": "Mover a la raíz",
            "移到其他文件夹": "Mover a otra carpeta",
            "批量移到其他文件夹": "Mover por lotes a otra carpeta",
            "合并到新文件夹": "Unir en una carpeta nueva",
            "合并到文件夹": "Unir en una carpeta",
            "将 %d 首歌曲移到回收站？": "¿Mover %d canciones a la papelera?",
            "导入 .smelody.txt 文件（可多选）": "Importar archivos .smelody.txt (varios)",
            "导入文件夹（不递归套娃，归到同名文件夹）": "Importar carpeta (sin anidar, a una carpeta del mismo nombre)",
            "批量导入文件夹": "Importar carpetas por lotes",
            "选择要导入的 .smelody.txt 文件（可多选）": "Elige archivos .smelody.txt para importar (varios)",
            "导入文件夹": "Importar carpeta",
            "导入备份文件夹（含套娃结构）": "Importar carpeta de copia (con estructura anidada)",
            "导入成功 (%d 首歌曲)": "Se importaron %d canciones",
            "输入文件夹名": "Introduce el nombre de la carpeta",
            "输入新文件夹名": "Introduce el nombre de la carpeta nueva",
            "套娃文件夹": "Carpeta anidada",
            "确定": "Aceptar",
            "取消": "Cancelar",
            "歌词导出": "Exportación de la letra",
            "歌曲信息": "Información de la canción",
            "歌词": "Letra",
            "创建时间": "Creado",
            "修改时间": "Modificado",
            "导出时间": "Exportado",
            "请先在歌曲语言中加入日语": "Añade primero el japonés a los idiomas de la canción",
            "导出为文本文件（含全部信息）": "Exportar como archivo de texto (con toda la información)",
            "将歌词的全部信息导出为文本文件": "Exporta toda la información de la letra a un archivo de texto",
            "导入歌曲": "Importar canción",
            "导入歌曲文件": "Importar archivo de canción",
            "选择要导入的 .smelody.txt 文件": "Elige el archivo .smelody.txt que quieres importar",
            "导入成功": "Importación correcta",
            "导入失败": "Error al importar",
            "数据管理": "Gestión de datos",
            "一键备份曲目库": "Copia de la biblioteca en un paso",
            "将所有歌曲按 .smelody.txt 格式打包到选定文件夹": "Empaqueta todas las canciones como .smelody.txt en la carpeta elegida",
            "备份": "Copia de seguridad",
            "成功备份 %d 首歌曲到\n%@": "Se copiaron %d canciones en\n%@",
            "成功 %d 首，失败 %d 首": "%d correctas, %d fallidas",
            "选择保存备份的文件夹": "Elige la carpeta para guardar la copia",
            "选择这里": "Elegir",
            "删除前显示确认弹窗": "Mostrar confirmación antes de eliminar",
            "删除歌曲、段落、灵感前提示确认（暂不可恢复）": "Confirma antes de borrar canciones, secciones o ideas (no se puede deshacer)",
            "确认删除": "Confirmar eliminación",
            "此操作暂不可恢复": "Esta acción no se puede deshacer",
            "不再提醒（可在设置中重新开启）": "No volver a preguntar (se puede activar en Ajustes)",
            "将删除歌曲": "Se eliminará la canción",
            "将删除段落": "Se eliminará la sección",
            "将删除条目": "Se eliminará el elemento",
            "将删除 %d 个段落": "Se eliminarán %d secciones",
            "包含": "contiene",
            "个段落": " secciones",
            "条灵感与设定": " ideas y ambientación",
            "条译文": " traducciones",
            "帮助": "Ayuda",
            "下载链接": "Enlace de descarga",
            "检查版本更新": "Buscar actualizaciones",
            "启动时检查更新": "Comprobar al iniciar",
            "启动时检查更新说明": "Al iniciar comprueba en silencio las versiones de GitHub y solo avisa si hay una más nueva.",
            "发现新版本": "Hay una versión nueva",
            "前往下载": "Descargar",
            "稍后": "Más tarde",
            "已是最新版本": "Ya tienes la última versión",
            "检查更新失败": "No se pudo comprobar la actualización",
            "正在检查更新": "Comprobando actualizaciones",
            "预览段落小字": "Texto pequeño de la sección",
            "预览段落小字说明": "El texto pequeño bajo cada sección de la vista previa: notas o traducción. Si está vacío, no se muestra.",
            "更新日志": "Registro de cambios",
            "查看更新日志": "Ver el registro de cambios",
            "查看每个版本的更新内容": "Ver los cambios de cada versión",
            "最新": "Más reciente",
            "使用指南": "Guía de uso",
            "软件介绍 + 各功能使用说明（随界面语言切换）": "Introducción de la app y guía de funciones",
            "技能炼成": "Habilidades integradas",
            "技能煉成": "Habilidades integradas",
            "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用": "Exporta las habilidades de letra de Simple Melody a un agente de IA",
            "Skill Integrated": "Skill Integrated",
            "スキル錬成": "Habilidades integradas",
            "词炼成": "Forja de letra",
            "曲炼成": "Forja musical",
            "导出 Skill 文件": "Exportar archivo de habilidad",
            "复制到剪贴板": "Copiar al portapapeles",
            "Skill 简介": "Resumen de la habilidad",
            "smelody-lyric-create": "smelody-lyric-create",
            "smelody-music-create": "smelody-music-create",
            "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）": "De la idea a un .smelody.txt completo (importable en Simple Melody)",
            "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）": ".smelody.txt → entrada para IA musical (SUNO / Udio)",
            "保存为": "Guardar como",
            "保存": "Guardar",
            "保存成功": "Guardado correctamente",
            "保存失败": "Error al guardar",
            "：找不到 SKILL.md 资源": ": no se encontró el recurso SKILL.md",
            "复制成功": "Copiado correctamente",
            "复制失败": "Error al copiar",
            "选择保存位置": "Elige dónde guardar",
            "Skill 文件（.md）": "Archivo de habilidad (.md)",
            "Skill 文件夹父目录": "Carpeta padre del directorio de habilidades",
            "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。": "La forja de letra convierte la idea en un .smelody.txt que se puede importar en Simple Melody.",
            "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。": "La forja musical resume el .smelody.txt en un archivo de dos partes listo para una IA musical (SUNO / Udio, etc.).",
            "典型工作流": "Flujo habitual",
            "完整工作流（推荐）": "Flujo completo (recomendado)",
            "第一步：做词炼成": "Paso 1: forja de letra",
            "第二步：做曲炼成": "Paso 2: forja musical",
            "第三步：交给 AI Agent 作曲": "Paso 3: pasarlo a un agente de IA",
            "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）": "Envía la idea a un agente de IA (si tiene herramientas SUNO/Udio)",
            "描述歌曲主题、风格、参考等": "Describe el tema, el estilo y las referencias",
            "触发词：": "Palabras de activación:",
            "触发词": "Palabras de activación",
            "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"": "\"Haz la forja de letra\" / \"Escribe la letra en formato smelody\" / \"Escribe una canción en formato Simple Melody\"",
            "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"": "\"Haz la forja musical\" / \"Prepara el prompt de SUNO\" / \"Prepara la letra para componer con IA\"",
            "输出": "Salida",
            "把完整歌词文件保存为 .smelody.txt": "Guarda el archivo completo de la letra como .smelody.txt",
            "在 Simple Melody 中导入": "Importar en Simple Melody",
            "把 .smelody.txt 歌词文件发给 AI Agent": "Envía el .smelody.txt al agente de IA",
            "AI 提炼出两段式输出文件": "La IA lo resume en un archivo de dos partes",
            "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框": "Pega la parte superior en el cuadro Lyrics de SUNO / Udio",
            "下半部分作曲建议作为 Style prompt 的一部分": "Usa la parte inferior como parte del prompt de estilo",
            "如果您无法理解以上内容请不要使用该功能": "Si no entiendes lo anterior, no uses esta función",
            "Skill需要移交给有文件处理能力的LLM": "La habilidad debe pasarse a un LLM que sí pueda manejar archivos",
            "否则无效": "de lo contrario no sirve",
            "血红色警示": "Aviso en rojo",
            "复制 Skill 文本": "Copiar el texto de la habilidad",
            "已复制到剪贴板": "Copiado al portapapeles",
            "词炼成：AI 输出完整 .smelody.txt": "Forja de letra: la IA escribe un .smelody.txt completo",
            "曲炼成：AI 输出两段式（歌词 + 作曲建议）": "Forja musical: la IA escribe dos partes (letra + sugerencias)",
            "删除": "Eliminar",
            "编辑": "Editar",
            "新建": "Nuevo",
            "搜索": "Buscar",
            "关闭": "Cerrar",
            "复制": "Copiar",
            "粘贴": "Pegar",
            "导出": "Exportar",
            "导入": "Importar",
            "曲目库": "Canciones",
            "首": "canción",
            "条记录": " registros",
            "搜索曲目": "Buscar canciones",
            "新建歌曲": "Canción nueva",
            "新建第一首": "Crear la primera canción",
            "新建段落": "Sección nueva",
            "还没有歌曲": "Aún no hay canciones",
            "没有匹配的歌曲": "No hay canciones que coincidan",
            "选择左侧的歌曲开始创作，或新建一首新歌。": "Elige una canción a la izquierda o crea una nueva.",
            "Simple Melody": "Simple Melody",
            "排序方式": "Orden",
            "手动排序": "Manual",
            "最近修改": "Modificado recientemente",
            "标题": "Título",
            "段": " secciones",
            "字": " caracteres",
            "BPM": "BPM",
            "Key": "Tono",
            "未命名": "Sin título",
            "歌曲标题": "Título de la canción",
            "艺术家": "Artista",
            "语言": "Idioma",
            "调式": "Tono",
            "标签（逗号分隔）": "Etiquetas (separadas por comas)",
            "收起": "Plegar",
            "展开": "Expandir",
            "导出为文本文件": "Exportar como archivo de texto",
            "复制全文到剪贴板": "Copiar todo al portapapeles",
            "段落笔记": "Notas de la sección",
            "段落类型": "Tipo de sección",
            "自定义段落名": "Nombre de sección personalizado",
            "应用": "Aplicar",
            "如 Spoken Word": "p. ej. Spoken Word",
            "上移": "Subir",
            "下移": "Bajar",
            "复制段落": "Duplicar sección",
            "上": "Arriba",
            "下": "Abajo",
            "前奏": "Introducción",
            "主歌": "Estrofa",
            "预副歌": "Pre-estribillo",
            "副歌": "Estribillo",
            "副歌后": "Post-estribillo",
            "桥段": "Puente",
            "记忆点": "Gancho",
            "叠句": "Estribillo repetido",
            "间奏": "Interludio",
            "独奏": "Solo",
            "尾奏": "Cierre",
            "终曲": "Coda",
            "自定义": "Personalizado",
            "添加段落": "Añadir sección",
            "正文": "Cuerpo",
            "读音摘要": "Vista previa de la pronunciación",
            "注音列表": "Lista de anotaciones",
            "添加读音": "Añadir lectura",
            "自动注音": "Furigana automático",
            "对日语汉字自动生成假名注音": "Genera furigana automáticamente para los kanji",
            "为指定位置的文字添加读音": "Añade la lectura del texto en la posición indicada",
            "清除注音选项": "Opciones para borrar anotaciones",
            "清除所有自动注音": "Borrar todas las anotaciones automáticas",
            "清除所有手动注音": "Borrar todas las anotaciones manuales",
            "在正文中的位置": "Posición en el cuerpo",
            "起始: %d": "Inicio: %d",
            "长度: %d": "Longitud: %d",
            "原文预览": "Vista previa del original",
            "原文": "Original",
            "假名读音": "Furigana",
            "拼音": "Pinyin",
            "Phonetic": "Fonética",
            "编辑读音": "Editar lectura",
            "自动标注日语假名": "Anotar furigana japonés automáticamente",
            "灵感与设定": "Ideas y ambientación",
            "灵感": "Inspiración",
            "设定": "Ambientación",
            "背景": "Trasfondo",
            "备注": "Nota",
            "全部": "Todo",
            "记录灵感、背景故事、设定...": "Anota inspiración, trasfondo y ambientación...",
            "还没有灵感或设定": "Aún no hay ideas ni ambientación",
            "在这里记录创作灵感、角色设定或背景故事。": "Anota aquí la inspiración, los personajes o la historia.",
            "这些内容不会出现在歌词正文里。": "Esto no aparece en el cuerpo de la letra.",
            "设置": "Ajustes",
            "主题": "Tema",
            "字体大小": "Tamaño de letra",
            "较小": "Más pequeño",
            "较大": "Más grande",
            "跟随系统": "Seguir el sistema",
            "浅色": "Claro",
            "深色": "Oscuro",
            "界面语言": "Idioma de la interfaz",
            "接入大模型": "Conectar un modelo de lenguaje",
            "供以后的注音、翻译等功能使用": "Para funciones posteriores como furigana y traducción",
            "供应商网址": "URL del proveedor",
            "模型名": "Nombre del modelo",
            "Imagine": "Imagine",
            "段落Imagine": "Imagine de sección",
            "翻译": "Traducción",
            "创意": "Creativo",
            "注音": "Furigana",
            "即将推出": "Próximamente",
            "只修改这一段": "Solo cambia esta sección",
            "也可填写歌曲语言、速度、调式和节拍": "También puede completar el título, el idioma, el tempo, la tonalidad y el compás",
            "提示词可留空": "Indicación opcional",
            "目标语言": "Idioma de destino",
            "开始": "Empezar",
            "继续": "Continuar",
            "依照当前格式": "Seguir el formato actual",
            "创意可能无法撤销或改错": "Lo creativo puede no deshacerse",
            "创意会改动歌词，可能无法撤销或出现错误。确定要继续吗？": "Lo creativo puede cambiar la letra de un modo irreversible o equivocado. ¿Seguir?",
            "段落Imagine不能改整首歌或其他段落": "El Imagine de sección no puede cambiar la canción entera u otras secciones",
            "测试连接": "Probar conexión",
            "连接成功": "Conexión correcta",
            "连接失败": "No se pudo conectar",
            "正在测试连接": "Probando la conexión",
            "请先填写供应商网址和 API Key": "Escribe primero la URL del proveedor y la clave de API",
            "回复格式无法识别，没有改动歌词": "La respuesta no trae los campos esperados, así que no se cambió la letra",
            "正在请模型处理": "Consultando al modelo",
            "按 Command-Esc 取消": "Pulsa Command-Esc para cancelar",
            "没有歌词的段落不会翻译，笔记也不会被当成歌词": "Las secciones sin letra no se traducen, y las notas no se tratan como letra",
            "模型名可以留空": "El nombre del modelo puede quedar vacío",
            "建议选用参数量更大的模型，以便翻译、注音和创作更准确": "Conviene un modelo de muchos parámetros para traducir, anotar la lectura y escribir con más precisión",
            "API Key": "API Key",
            "清除": "Borrar",
            "首选语言": "Idioma preferido",
            "歌曲语言（可多选）": "Idiomas de la canción (varios)",
            "日语": "Japonés",
            "简体中文": "Chino simplificado",
            "繁体中文": "Chino tradicional",
            "英语": "Inglés",
            "韩语": "Coreano",
            "西班牙语": "Español",
            "法语": "Francés",
            "德语": "Alemán",
            "意大利语": "Italiano",
            "葡萄牙语": "Portugués",
            "选择语言": "Elegir idiomas",
            "已选": "Seleccionado",
            "未选": "No seleccionado",
            "歌词语言": "Idioma de la letra",
            "自动识别系统语言": "Detectar el idioma del sistema",
            "应用启动时检测系统语言": "Detectar el idioma del sistema al iniciar",
            "Simple Melody 帮助": "Ayuda de Simple Melody",
            "暂无帮助文档，请查看 README.md": "No hay documentación de ayuda. Consulta README.md.",
            "关于 Simple Melody": "Acerca de Simple Melody",
            "版本": "Versión",
            "v1.1 · Apple Silicon Native": "v1.1 · Apple Silicon nativo",
            "灵感分栏": "Panel de ideas",
            "显示/隐藏灵感与设定分栏": "Mostrar u ocultar el panel de ideas y ambientación",
            "Apple Silicon 原生": "Nativo de Apple Silicon",
            "平台": "Plataforma",
            "开发者": "Desarrollador",
            "自动标注日语假音": "Anotar furigana japonés automáticamente",
            "批量备份": "Copia de seguridad por lotes",
        ],
    ]
}
