// Localization/String+Localized.swift
// 字符串本地化
// 用 L("key") 调用，自动从 LocalizationManager.shared.language 查表

import Foundation
import SwiftUI

/// 简化的本地化函数
/// - Parameter key: 字符串 key
/// - Returns: 当前语言的翻译文本，若无翻译则返回 key 本身
func L(_ key: String) -> String {
    LocalizationManager.shared.localized(key)
}

extension String {
    /// 带参数格式化的本地化
    /// 例如: "起始: %d".localized(with: 5) => 当前语言下的 "起始: 5"
    func localized(with arguments: CVarArg...) -> String {
        let template = L(self)
        return withVaList(arguments) { ptr in
            NSString(format: template, arguments: ptr) as String
        }
    }
}

extension LocalizationManager {
    /// 查表翻译
    func localized(_ key: String) -> String {
        let table = Self.translationTable[language] ?? Self.translationTable[.english] ?? [:]
        return table[key] ?? key
    }

    /// 全部翻译表（key -> 各语言翻译）
    private static let translationTable: [AppLanguage: [String: String]] = [
        .simplifiedChinese: [
            "key": "key",
            "专辑": "专辑",
            "从 .smelody.txt 文件导入歌曲": "从 .smelody.txt 文件导入歌曲",
            "副本": "副本",
            "备份曲目库": "备份曲目库",
            "导出歌词": "导出歌词",
            "将删除注音": "将删除注音",
            "将清除 %d 条手动注音": "将清除 %d 条手动注音",
            "将清除 %d 条自动注音": "将清除 %d 条自动注音",
            "将覆盖 %d 条现有的自动注音": "将覆盖 %d 条现有的自动注音",
            "展开元信息": "展开元信息",
            "展开元信息（语言/BPM/调式/标签）": "展开元信息（语言/BPM/调式/标签）",
            "折叠": "折叠",
            "文件格式无效": "文件格式无效",
            "新歌曲": "新歌曲",
            "标签": "标签",
            "缺少歌曲元信息": "缺少歌曲元信息",
            "自动注音（仅日语段落）": "自动注音（仅日语段落）",
            "读取失败": "读取失败",
            "重新生成自动注音": "重新生成自动注音",
            "长按段落任意位置可拖动重排": "长按段落任意位置可拖动重排",
            "上移至顶部": "上移至顶部",
            "下移至底部": "下移至底部",
            "段落拖动": "段落拖动",
            "段落拖动开关说明": "开启后段落可拖动重排。注意：拖动段落到歌词编辑栏时可能把代码嵌入文本中，且与左滑删除功能冲突。",
            "开启段落拖动功能？": "开启段落拖动功能？",
            "我已知晓风险，继续开启": "我已知晓风险，继续开启",
            "拖动段落重排": "拖动段落重排",

            // ====== 段落类型预设（v1.4） ======
            "section.type.Intro"      : "前奏",
            "section.type.Verse"      : "主歌",
            "section.type.Pre-Chorus" : "预副歌",
            "section.type.Chorus"     : "副歌",
            "section.type.Post-Chorus": "副歌后",
            "section.type.Bridge"     : "桥段",
            "section.type.Hook"       : "记忆点",
            "section.type.Refrain"    : "叠句",
            "section.type.Interlude"  : "间奏",
            "section.type.Solo"       : "独奏",
            "section.type.Outro"      : "尾奏",
            "section.type.Coda"       : "终曲",
            "section.type.Custom"     : "自定义",
            // ====== 灵感类型预设（v1.4） ======
            "idea.type.Inspiration"   : "灵感",
            "idea.type.Setting"       : "设定",
            "idea.type.Background"    : "背景",
            "idea.type.Note"          : "备注",

// ====== v1.5 新增 ======
            "笔记": "笔记",
            "更多": "更多",
            "中文": "中文",
            "文件夹": "文件夹",
            "新文件夹": "新文件夹",
            "归并到文件夹": "归并到文件夹",
            "重命名": "重命名",
            "解散文件夹": "解散文件夹",
            "备份文件夹": "备份文件夹",
            "导出文件夹": "导出文件夹",
            "选中 %d 项": "选中 %d 项",
            "已选中": "已选中",
            "取消选择": "取消选择",
            "选择歌曲": "选择歌曲",
            "目标文件夹": "目标文件夹",
            "新建文件夹": "新建文件夹",
            "歌单": "歌单",
            "歌曲类型": "歌曲类型",
            "回收站": "回收站",
            "移到回收站": "移到回收站",
            "永久删除": "永久删除",
            "将歌曲移到回收站": "将歌曲移到回收站？",
            "将歌曲永久删除": "将歌曲永久删除？此操作不可恢复！",
            "将文件夹永久删除": "将永久删除文件夹及其中所有歌曲？此操作不可恢复！",
            "清空回收站": "清空回收站",
            "在回收站中再次删除才能永久删除": "在回收站中再次删除才能永久删除",
            "已选 %d 项": "已选 %d 项",
            "已选 1 项": "已选 1 项",
            // ====== v1.6 节拍 / 文件夹操作 ======
            "节拍": "节拍",
            "节拍器": "节拍器",
            "停止": "停止",
            "停止节拍器": "停止节拍器",
            "启动节拍器": "启动节拍器",
            // ====== v1.7 歌词预览 / UI补充 ======
            "歌词预览": "歌词预览",
            "预览歌词": "预览歌词",
            "未命名歌曲": "未命名歌曲",
            "未知艺术家": "未知艺术家",
            "暂无歌词": "暂无歌词",
            "双击跳转到段落": "双击跳转到该段落",
            "正在预览": "正在预览",
            "展开 / 收起元信息": "展开 / 收起元信息",

            "删除文件夹": "删除文件夹",
            "双击展开/折叠文件夹": "双击展开/折叠文件夹",
            "确定要删除文件夹": "确定要删除文件夹？",

            "备份曲目库（含文件夹结构）": "备份曲目库（含文件夹结构）",

            // ====== v1.5.2 批量操作 ======
            "批量导出": "批量导出",
            "批量移到回收站": "批量移到回收站",
            "批量恢复": "批量恢复",
            "批量永久删除": "批量永久删除",
            "批量移到根目录": "批量移到根目录",
            "移到根目录": "移到根目录",
            "移到其他文件夹": "移到其他文件夹",
            "批量移到其他文件夹": "批量移到其他文件夹",
            "合并到新文件夹": "合并到新文件夹",
            "合并到文件夹": "合并到文件夹",
            "将 %d 首歌曲移到回收站？": "将 %d 首歌曲移到回收站？",
            "导入 .smelody.txt 文件（可多选）": "导入 .smelody.txt 文件（可多选）",
            "导入文件夹（不递归套娃，归到同名文件夹）": "导入文件夹（不递归套娃，归到同名文件夹）",
            "批量导入文件夹": "批量导入文件夹",
            "选择要导入的 .smelody.txt 文件（可多选）": "选择要导入的 .smelody.txt 文件（可多选）",
            "导入文件夹": "导入文件夹",
            "导入备份文件夹（含套娃结构）": "导入备份文件夹（含套娃结构）",
            "导入成功 (%d 首歌曲)": "导入成功 (%d 首歌曲)",
            "输入文件夹名": "输入文件夹名",
            "输入新文件夹名": "输入新文件夹名",
            "套娃文件夹": "套娃文件夹",

            // ====== 通用 ======
            "确定": "确定",
            "取消": "取消",
            "歌词导出": "歌词导出",
            "歌曲信息": "歌曲信息",
            "歌词": "歌词",
            "创建时间": "创建时间",
            "修改时间": "修改时间",
            "导出时间": "导出时间",
            "请先在歌曲语言中加入日语": "请先在歌曲语言中加入日语",
            "导出为文本文件（含全部信息）": "导出为文本文件（含全部信息）",
            "将歌词的全部信息导出为文本文件": "将歌词的全部信息导出为文本文件",
            "导入歌曲": "导入歌曲",
            "导入歌曲文件": "导入歌曲文件",
            "选择要导入的 .smelody.txt 文件": "选择要导入的 .smelody.txt 文件",
            "导入成功": "导入成功",
            "导入失败": "导入失败",
            "数据管理": "数据管理",
            "一键备份曲目库": "一键备份曲目库",
            "将所有歌曲按 .smelody.txt 格式打包到选定文件夹": "将所有歌曲按 .smelody.txt 格式打包到选定文件夹",
            "备份": "备份",
            "成功备份 %d 首歌曲到\n%@": "成功备份 %d 首歌曲到\n%@",
            "成功 %d 首，失败 %d 首": "成功 %d 首，失败 %d 首",
            "选择保存备份的文件夹": "选择保存备份的文件夹",
            "选择这里": "选择这里",
            "删除前显示确认弹窗": "删除前显示确认弹窗",
            "删除歌曲、段落、灵感前提示确认（暂不可恢复）": "删除歌曲、段落、灵感前提示确认（暂不可恢复）",
            "确认删除": "确认删除",
            "此操作暂不可恢复": "此操作暂不可恢复",
            "不再提醒（可在设置中重新开启）": "不再提醒（可在设置中重新开启）",
            "将删除歌曲": "将删除歌曲",
            "将删除段落": "将删除段落",
            "将删除条目": "将删除条目",
            "将删除 %d 个段落": "将删除 %d 个段落",
            "包含": "包含",
            "个段落": "个段落",
            "条灵感与设定": "条灵感与设定",
            "帮助": "帮助",
            "下载链接": "下载链接",
            "更新日志": "更新日志",
            "查看更新日志": "查看更新日志",
            "查看每个版本的更新内容": "查看每个版本的更新内容",
            "最新": "最新",
            "使用指南": "使用指南",
            "软件介绍 + 各功能使用说明（随界面语言切换）": "软件介绍 + 各功能使用说明",
            "技能炼成": "技能炼成",
            "技能煉成": "技能煉成",
            "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用": "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用",
            "Skill Integrated": "Skill Integrated",
            "スキル錬成": "スキル錬成",
            "词炼成": "词炼成",
            "曲炼成": "曲炼成",
            "导出 Skill 文件": "导出 Skill 文件",
            "复制到剪贴板": "复制到剪贴板",
            "Skill 简介": "Skill 简介",
            "smelody-lyric-create": "smelody-lyric-create",
            "smelody-music-create": "smelody-music-create",
            "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）": "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）",
            "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）": "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）",
            "保存为": "保存为",
            "保存": "保存",
            "保存成功": "保存成功",
            "保存失败": "保存失败",
            "：找不到 SKILL.md 资源": "：找不到 SKILL.md 资源",
            "复制成功": "复制成功",
            "复制失败": "复制失败",
            "选择保存位置": "选择保存位置",
            "Skill 文件（.md）": "Skill 文件（.md）",
            "Skill 文件夹父目录": "Skill 文件夹父目录",
            "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。": "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。",
            "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。": "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。",
            "典型工作流": "典型工作流",
            "完整工作流（推荐）": "完整工作流（推荐）",
            "第一步：做词炼成": "第一步：做词炼成",
            "第二步：做曲炼成": "第二步：做曲炼成",
            "第三步：交给 AI Agent 作曲": "第三步：交给 AI Agent 作曲",
            "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）": "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）",
            "描述歌曲主题、风格、参考等": "描述歌曲主题、风格、参考等",
            "触发词：": "触发词：",
            "触发词": "触发词",
            "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"": "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"",
            "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"": "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"",
            "输出": "输出",
            "把完整歌词文件保存为 .smelody.txt": "把完整歌词文件保存为 .smelody.txt",
            "在 Simple Melody 中导入": "在 Simple Melody 中导入",
            "把 .smelody.txt 歌词文件发给 AI Agent": "把 .smelody.txt 歌词文件发给 AI Agent",
            "AI 提炼出两段式输出文件": "AI 提炼出两段式输出文件",
            "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框": "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框",
            "下半部分作曲建议作为 Style prompt 的一部分": "下半部分作曲建议作为 Style prompt 的一部分",
            "如果您无法理解以上内容请不要使用该功能": "如果您无法理解以上内容请不要使用该功能",
            "Skill 需要移交给拥有 Agent 能力的智能体": "Skill 需要移交给拥有 Agent 能力的智能体",
            "否则无效": "否则无效",
            "血红色警示": "血红色警示",
            "复制 Skill 文本": "复制 Skill 文本",
            "已复制到剪贴板": "已复制到剪贴板",
            "词炼成：AI 输出完整 .smelody.txt": "词炼成：AI 输出完整 .smelody.txt",
            "曲炼成：AI 输出两段式（歌词 + 作曲建议）": "曲炼成：AI 输出两段式（歌词 + 作曲建议）",
            "删除": "删除",
            "编辑": "编辑",
            "新建": "新建",
            "搜索": "搜索",
            "关闭": "关闭",
            "复制": "复制",
            "粘贴": "粘贴",
            "导出": "导出",
            "导入": "导入",

            // ====== 主界面 ======
            "曲目库": "曲目库",
            "首": "首",
            "条记录": "条记录",
            "搜索曲目": "搜索曲目",
            "新建歌曲": "新建歌曲",
            "新建第一首": "新建第一首",
            "新建段落": "新建段落",
            "还没有歌曲": "还没有歌曲",
            "没有匹配的歌曲": "没有匹配的歌曲",
            "选择左侧的歌曲开始创作，或新建一首新歌。": "选择左侧的歌曲开始创作，或新建一首新歌。",
            "Simple Melody": "Simple Melody",

            // 排序
            "排序方式": "排序方式",
            "手动排序": "手动排序",
            "最近修改": "最近修改",
            "标题": "标题",

            // 段落计数等
            "段": "段",
            "字": "字",
            "BPM": "BPM",
            "Key": "Key",
            "未命名": "未命名",

            // ====== 歌曲编辑 ======
            "歌曲标题": "歌曲标题",
            "艺术家": "艺术家",
            "语言": "语言",
            "调式": "调式",
            "标签（逗号分隔）": "标签（逗号分隔）",
            "收起": "收起",
            "展开": "展开",
            "导出为文本文件": "导出为文本文件",
            "复制全文到剪贴板": "复制全文到剪贴板",
            "段落笔记": "段落笔记",
            "段落类型": "段落类型",
            "自定义段落名": "自定义段落名",
            "应用": "应用",
            "如 Spoken Word": "如 Spoken Word",
            "上移": "上移",
            "下移": "下移",
            "复制段落": "复制段落",
            "上": "上",
            "下": "下",

            // ====== 段落类型 ======
            "前奏": "前奏",
            "主歌": "主歌",
            "预副歌": "预副歌",
            "副歌": "副歌",
            "副歌后": "副歌后",
            "桥段": "桥段",
            "记忆点": "记忆点",
            "叠句": "叠句",
            "间奏": "间奏",
            "独奏": "独奏",
            "尾奏": "尾奏",
            "终曲": "终曲",
            "自定义": "自定义",
            "添加段落": "添加段落",

            // ====== 注音 ======
            "正文": "正文",
            "读音摘要": "读音摘要",
            "注音列表": "注音列表",
            "添加读音": "添加读音",
            "自动注音": "自动注音",
            "对日语汉字自动生成假名注音": "对日语汉字自动生成假名注音",
            "为指定位置的文字添加读音": "为指定位置的文字添加读音",
            "清除注音选项": "清除注音选项",
            "清除所有自动注音": "清除所有自动注音",
            "清除所有手动注音": "清除所有手动注音",
            "在正文中的位置": "在正文中的位置",
            "起始: %d": "起始: %d",
            "长度: %d": "长度: %d",
            "原文预览": "原文预览",
            "原文": "原文",
            "假名读音": "假名读音",
            "拼音": "拼音",
            "Phonetic": "Phonetic",
            "编辑读音": "编辑读音",
            "自动标注日语假名": "自动标注日语假名",

            // ====== 灵感分栏 ======
            "灵感与设定": "灵感与设定",
            "灵感": "灵感",
            "设定": "设定",
            "背景": "背景",
            "备注": "备注",
            "全部": "全部",
            "记录灵感、背景故事、设定...": "记录灵感、背景故事、设定...",
            "还没有灵感或设定": "还没有灵感或设定",
            "在这里记录创作灵感、角色设定或背景故事。": "在这里记录创作灵感、角色设定或背景故事。",
            "这些内容不会出现在歌词正文里。": "这些内容不会出现在歌词正文里。",

            // ====== 设置 ======
            "设置": "设置",
            "主题": "主题",
            "跟随系统": "跟随系统",
            "浅色": "浅色",
            "深色": "深色",
            "界面语言": "界面语言",
            "首选语言": "首选语言",
            "歌曲语言（可多选）": "歌曲语言（可多选）",

            // ====== 歌曲语言名称（多选 chip） ======
            "日语": "日语",
            "简体中文": "简体中文",
            "繁体中文": "繁体中文",
            "英语": "英语",
            "韩语": "韩语",
            "西班牙语": "西班牙语",
            "法语": "法语",
            "德语": "德语",
            "意大利语": "意大利语",
            "葡萄牙语": "葡萄牙语",
            "选择语言": "选择语言",
            "已选": "已选",
            "未选": "未选",
            "歌词语言": "歌词语言",
            "自动识别系统语言": "自动识别系统语言",
            "应用启动时检测系统语言": "应用启动时检测系统语言",

            // ====== 菜单 ======
            "Simple Melody 帮助": "Simple Melody 帮助",

            // ====== 通知 ======
            "暂无帮助文档，请查看 README.md": "暂无帮助文档，请查看 README.md",

            // ====== 版本 ======
            "关于 Simple Melody": "关于 Simple Melody",
            "版本": "版本",
            "v1.1 · Apple Silicon Native": "v1.1 · Apple Silicon Native",

            // ====== 状态 ======
            "灵感分栏": "灵感分栏",
            "显示/隐藏灵感与设定分栏": "显示/隐藏灵感与设定分栏",
            "Apple Silicon 原生": "Apple Silicon 原生",
            "平台": "平台",
            "开发者": "开发者",

        ],

        .traditionalChinese: [
                        "section.type.Intro": "前奏",
            "section.type.Verse": "主歌",
            "section.type.Pre-Chorus": "預副歌",
            "section.type.Chorus": "副歌",
            "section.type.Post-Chorus": "副歌後",
            "section.type.Bridge": "橋段",
            "section.type.Hook": "記憶點",
            "section.type.Refrain": "疊句",
            "section.type.Interlude": "間奏",
            "section.type.Solo": "獨奏",
            "section.type.Outro": "尾奏",
            "section.type.Coda": "終曲",
            "section.type.Custom": "自訂",
            "idea.type.Inspiration": "靈感",
            "idea.type.Setting": "設定",
            "idea.type.Background": "背景",
            "idea.type.Note": "備註",
// ====== v1.5 新增 ======
            "笔记": "筆記",
            "更多": "更多",
            "中文": "中文",
            "文件夹": "文件夾",
            "新文件夹": "新檔案夾",
            "归并到文件夹": "歸併到檔案夾",
            "重命名": "重新命名",
            "解散文件夹": "解散檔案夾",
            "备份文件夹": "備份檔案夾",
            "导出文件夹": "匯出檔案夾",
            "选中 %d 项": "已選 %d 項",
            "已选中": "已選中",
            "取消选择": "取消選取",
            "选择歌曲": "選擇歌曲",
            "目标文件夹": "目標檔案夾",
            "新建文件夹": "新建檔案夾",
            "歌单": "歌單",
            "歌曲类型": "歌曲類型",
            "回收站": "回收桶",
            "移到回收站": "移到回收桶",
            "永久删除": "永久刪除",
            "将歌曲移到回收站": "將歌曲移到回收桶？",
            "将歌曲永久删除": "將歌曲永久刪除？此操作不可復原！",
            "将文件夹永久删除": "將永久刪除檔案夾及其中所有歌曲？此操作不可復原！",
            "清空回收站": "清空回收桶",
            "在回收站中再次删除才能永久删除": "在回收桶中再次刪除才能永久刪除",
            "已选 %d 项": "已選 %d 項",
            "已选 1 项": "已選 1 項",
            // ====== v1.6 节拍 / 文件夹操作 ======
            "节拍": "節拍",
            "节拍器": "節拍器",
            "停止": "停止",
            "停止节拍器": "停止節拍器",
            "启动节拍器": "啟動節拍器",
            // ====== v1.7 歌词预览 / UI补充 ======
            "歌词预览": "歌詞預覽",
            "预览歌词": "預覽歌詞",
            "未命名歌曲": "未命名歌曲",
            "未知艺术家": "未知藝術家",
            "暂无歌词": "暫無歌詞",
            "双击跳转到段落": "雙擊跳轉到該段落",
            "正在预览": "正在預覽",
            "展开 / 收起元信息": "展開 / 收起元信息",

            "删除文件夹": "刪除檔案夾",
            "双击展开/折叠文件夹": "雙擊展開/折疊檔案夾",
            "确定要删除文件夹": "確定要刪除檔案夾？",

            "备份曲目库（含文件夹结构）": "備份歌單庫（含檔案夾結構）",
            "导入文件夹": "匯入檔案夾",
            // ====== v1.5.2 批量操作 ======
            "批量导出": "批量匯出",
            "批量移到回收站": "批量移到回收桶",
            "批量恢复": "批量恢復",
            "批量永久删除": "批量永久刪除",
            "批量移到根目录": "批量移到根目錄",
            "移到根目录": "移到根目錄",
            "移到其他文件夹": "移到其他資料夾",
            "批量移到其他文件夹": "批量移到其他資料夾",
            "合并到新文件夹": "合併到新檔案夾",
            "合并到文件夹": "合併到檔案夾",
            "将 %d 首歌曲移到回收站？": "將 %d 首歌曲移到回收桶？",
            "导入 .smelody.txt 文件（可多选）": "匯入 .smelody.txt 文件（可多選）",
            "导入文件夹（不递归套娃，归到同名文件夹）": "匯入檔案夾（不遞歸套娃，歸到同名檔案夾）",
            "批量导入文件夹": "批量匯入檔案夾",
            "选择要导入的 .smelody.txt 文件（可多选）": "選擇要匯入的 .smelody.txt 文件（可多選）",

            "导入备份文件夹（含套娃结构）": "匯入備份檔案夾（含套娃結構）",
            "导入成功 (%d 首歌曲)": "匯入成功（%d 首歌曲）",
            "输入文件夹名": "輸入檔案夾名",
            "输入新文件夹名": "輸入新檔案夾名",
            "套娃文件夹": "套娃檔案夾",

"确定": "確定",
            "取消": "取消",
            "歌词导出": "歌詞匯出",
            "歌曲信息": "歌曲資訊",
            "歌词": "歌詞",
            "创建时间": "建立時間",
            "修改时间": "修改時間",
            "导出时间": "匯出時間",
            "请先在歌曲语言中加入日语": "請先在歌曲語言中加入日語",
            "导出为文本文件（含全部信息）": "匯出為文字檔（含全部資訊）",
            "将歌词的全部信息导出为文本文件": "將歌詞的全部資訊匯出為文字檔",
            "导入歌曲": "匯入歌曲",
            "导入歌曲文件": "匯入歌曲檔案",
            "选择要导入的 .smelody.txt 文件": "選擇要匯入的 .smelody.txt 檔案",
            "导入成功": "匯入成功",
            "导入失败": "匯入失敗",
            "数据管理": "資料管理",
            "一键备份曲目库": "一鍵備份曲目庫",
            "将所有歌曲按 .smelody.txt 格式打包到选定文件夹": "將所有歌曲按 .smelody.txt 格式打包到選定資料夾",
            "备份": "備份",
            "成功备份 %d 首歌曲到\n%@": "成功備份 %d 首歌曲到\n%@",
            "成功 %d 首，失败 %d 首": "成功 %d 首，失敗 %d 首",
            "选择保存备份的文件夹": "選擇儲存備份的資料夾",
            "选择这里": "選擇這裡",
            "删除前显示确认弹窗": "刪除前顯示確認彈窗",
            "删除歌曲、段落、灵感前提示确认（暂不可恢复）": "刪除歌曲、段落、靈感前提示確認（暫不可恢復）",
            "确认删除": "確認刪除",
            "此操作暂不可恢复": "此操作暫不可恢復",
            "不再提醒（可在设置中重新开启）": "不再提醒（可在設定中重新開啟）",
            "将删除歌曲": "將刪除歌曲",
            "将删除段落": "將刪除段落",
            "将删除条目": "將刪除條目",
            "将删除 %d 个段落": "將刪除 %d 個段落",
            "包含": "包含",
            "个段落": "個段落",
            "条灵感与设定": "條靈感與設定",
            "帮助": "說明",
            "下载链接": "下載連結",
            "更新日志": "更新日誌",
            "查看更新日志": "查看更新日誌",
            "查看每个版本的更新内容": "查看每個版本的更新內容",
            "使用指南": "使用指南",
            "技能炼成": "技能煉成",
            "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用": "把 Simple Melody 的歌詞 Skill 匯出給 AI Agent 用",
            "词炼成": "詞煉成",
            "曲炼成": "曲煉成",
            "导出 Skill 文件": "匯出 Skill 檔案",
            "复制到剪贴板": "複製到剪貼簿",
            "Skill 简介": "Skill 簡介",
            "smelody-lyric-create": "smelody-lyric-create",
            "smelody-music-create": "smelody-music-create",
            "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）": "把創作需求 → 完整的 .smelody.txt（可匯入 Simple Melody）",
            "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）": "把 .smelody.txt → 作曲 AI 輸入（SUNO / Udio）",
            "保存为": "儲存為",
            "保存成功": "儲存成功",
            "保存失败": "儲存失敗",
            "：找不到 SKILL.md 资源": "：找不到 SKILL.md 資源",
            "复制成功": "複製成功",
            "复制失败": "複製失敗",
            "选择保存位置": "選擇儲存位置",
            "Skill 文件（.md）": "Skill 檔案（.md）",
            "Skill 文件夹父目录": "Skill 資料夾父目錄",
            "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。": "詞煉成是把創作需求轉化為可匯入 Simple Melody 的 .smelody.txt 歌詞檔案。",
            "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。": "曲煉成是把 .smelody.txt 提煉為作曲 AI（SUNO / Udio 等）可直接使用的兩段式檔案。",
            "典型工作流": "典型工作流",
            "完整工作流（推荐）": "完整工作流（推薦）",
            "第一步：做词炼成": "第一步：做詞煉成",
            "第二步：做曲炼成": "第二步：做曲煉成",
            "第三步：交给 AI Agent 作曲": "第三步：交給 AI Agent 作曲",
            "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）": "把創作需求發給 AI Agent（如有 SUNO/Udio 工具）",
            "描述歌曲主题、风格、参考等": "描述歌曲主題、風格、參考等",
            "触发词：": "觸發詞：",
            "触发词": "觸發詞",
            "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"": "\"做詞煉成\" / \"按 smelody 格式寫歌詞\" / \"寫一首 Simple Melody 格式的歌詞\"",
            "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"": "\"做曲煉成\" / \"準備 SUNO 提示詞\" / \"整理歌詞給 AI 作曲\"",
            "输出": "輸出",
            "把完整歌词文件保存为 .smelody.txt": "把完整歌詞檔案儲存為 .smelody.txt",
            "在 Simple Melody 中导入": "在 Simple Melody 中匯入",
            "把 .smelody.txt 歌词文件发给 AI Agent": "把 .smelody.txt 歌詞檔案發給 AI Agent",
            "AI 提炼出两段式输出文件": "AI 提煉出兩段式輸出檔案",
            "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框": "上半部分歌詞貼上到 SUNO / Udio 的 Lyrics 輸入框",
            "下半部分作曲建议作为 Style prompt 的一部分": "下半部分作曲建議作為 Style prompt 的一部分",
            "如果您无法理解以上内容请不要使用该功能": "如果您無法理解以上內容請不要使用該功能",
            "Skill 需要移交给拥有 Agent 能力的智能体": "Skill 需要移交給擁有 Agent 能力的智能體",
            "否则无效": "否則無效",
            "复制 Skill 文本": "複製 Skill 文字",
            "已复制到剪贴板": "已複製到剪貼簿",
            "词炼成：AI 输出完整 .smelody.txt": "詞煉成：AI 輸出完整 .smelody.txt",
            "曲炼成：AI 输出两段式（歌词 + 作曲建议）": "曲煉成：AI 輸出兩段式（歌詞 + 作曲建議）",
            "软件介绍 + 各功能使用说明（随界面语言切换）": "軟體介紹 + 各功能使用說明",
            "最新": "最新",
            "版本": "版本",
            "开发者": "開發者",
            "平台": "平台",
            "Apple Silicon 原生": "Apple Silicon 原生",
            "保存": "儲存",
            "删除": "刪除",
            "编辑": "編輯",
            "新建": "新增",
            "搜索": "搜尋",
            "关闭": "關閉",
            "复制": "複製",
            "粘贴": "貼上",
            "导出": "匯出",
            "导入": "匯入",

            "曲目库": "曲目庫",
            "首": "首",
            "条记录": "條記錄",
            "搜索曲目": "搜尋曲目",
            "新建歌曲": "新增歌曲",
            "新建第一首": "新增第一首",
            "新建段落": "新增段落",
            "还没有歌曲": "還沒有歌曲",
            "没有匹配的歌曲": "沒有符合的歌曲",
            "选择左侧的歌曲开始创作，或新建一首新歌。": "選擇左側的歌曲開始創作，或新增一首新歌。",
            "Simple Melody": "Simple Melody",

            "排序方式": "排序方式",
            "手动排序": "手動排序",
            "最近修改": "最近修改",
            "标题": "標題",

            "段": "段",
            "字": "字",
            "BPM": "BPM",
            "Key": "Key",
            "未命名": "未命名",

            "歌曲标题": "歌曲標題",
            "艺术家": "藝術家",
            "语言": "語言",
            "调式": "調式",
            "标签（逗号分隔）": "標籤（逗號分隔）",
            "收起": "收起",
            "展开": "展開",
            "导出为文本文件": "匯出為文字檔",
            "复制全文到剪贴板": "複製全文到剪貼簿",
            "段落笔记": "段落筆記",
            "段落类型": "段落類型",
            "自定义段落名": "自訂段落名",
            "应用": "套用",
            "如 Spoken Word": "如 Spoken Word",
            "上移": "上移",
            "下移": "下移",
            "复制段落": "複製段落",
            "上": "上",
            "下": "下",

            "前奏": "前奏",
            "主歌": "主歌",
            "预副歌": "預副歌",
            "副歌": "副歌",
            "副歌后": "副歌後",
            "桥段": "橋段",
            "记忆点": "記憶點",
            "叠句": "疊句",
            "间奏": "間奏",
            "独奏": "獨奏",
            "尾奏": "尾奏",
            "终曲": "終曲",
            "自定义": "自訂",
            "添加段落": "新增段落",

            "正文": "正文",
            "读音摘要": "讀音摘要",
            "注音列表": "注音列表",
            "添加读音": "新增讀音",
            "自动注音": "自動注音",
            "对日语汉字自动生成假名注音": "對日語漢字自動產生假名注音",
            "为指定位置的文字添加读音": "為指定位置的文字新增讀音",
            "清除注音选项": "清除注音選項",
            "清除所有自动注音": "清除所有自動注音",
            "清除所有手动注音": "清除所有手動注音",
            "在正文中的位置": "在正文中的位置",
            "起始: %d": "起始: %d",
            "长度: %d": "長度: %d",
            "原文预览": "原文預覽",
            "原文": "原文",
            "假名读音": "假名讀音",
            "拼音": "拼音",
            "Phonetic": "Phonetic",
            "编辑读音": "編輯讀音",
            "自动标注日语假名": "自動標註日語假名",

            "灵感与设定": "靈感與設定",
            "灵感": "靈感",
            "设定": "設定",
            "背景": "背景",
            "备注": "備註",
            "全部": "全部",
            "记录灵感、背景故事、设定...": "記錄靈感、背景故事、設定...",
            "还没有灵感或设定": "還沒有靈感或設定",
            "在这里记录创作灵感、角色设定或背景故事。": "在這裡記錄創作靈感、角色設定或背景故事。",
            "这些内容不会出现在歌词正文里。": "這些內容不會出現在歌詞正文裡。",

            "设置": "設定",
            "主题": "主題",
            "跟随系统": "跟隨系統",
            "浅色": "淺色",
            "深色": "深色",
            "界面语言": "介面語言",
            "首选语言": "首選語言",
            "歌曲语言（可多选）": "歌曲語言（可多選）",

            "日语": "日語",
            "简体中文": "簡體中文",
            "繁体中文": "繁體中文",
            "英语": "英語",
            "韩语": "韓語",
            "西班牙语": "西班牙語",
            "法语": "法語",
            "德语": "德語",
            "意大利语": "意大利語",
            "葡萄牙语": "葡萄牙語",
            "选择语言": "選擇語言",
            "已选": "已選",
            "未选": "未選",
            "歌词语言": "歌詞語言",
            "自动识别系统语言": "自動識別系統語言",
            "应用启动时检测系统语言": "應用啟動時偵測系統語言",

            "Simple Melody 帮助": "Simple Melody 說明",

            "暂无帮助文档，请查看 README.md": "暫無說明文件，請查看 README.md",

            "关于 Simple Melody": "關於 Simple Melody",
            "v1.1 · Apple Silicon Native": "v1.1 · Apple Silicon Native",

            "灵感分栏": "靈感分欄",
            "显示/隐藏灵感与设定分栏": "顯示/隱藏靈感與設定分欄",
            "专辑": "專輯",
            "从 .smelody.txt 文件导入歌曲": "從 .smelody.txt 檔案匯入歌曲",
            "副本": "副本",
            "备份曲目库": "備份曲目庫",
            "导出歌词": "匯出歌詞",
            "将删除注音": "將刪除注音",
            "将清除 %d 条手动注音": "將清除 %d 條手動注音",
            "将清除 %d 条自动注音": "將清除 %d 條自動注音",
            "将覆盖 %d 条现有的自动注音": "將覆蓋 %d 條現有的自動注音",
            "展开元信息": "展開元資訊",
            "展开元信息（语言/BPM/调式/标签）": "展開元資訊（語言/BPM/調式/標籤）",
            "折叠": "折疊",
            "文件格式无效": "檔案格式無效",
            "新歌曲": "新歌曲",
            "标签": "標籤",
            "缺少歌曲元信息": "缺少歌曲元資訊",
            "自动注音（仅日语段落）": "自動注音（僅日語段落）",
            "读取失败": "讀取失敗",
            "重新生成自动注音": "重新產生自動注音",
            "长按段落任意位置可拖动重排": "長按段落任意位置可拖動重排",
            "上移至顶部": "上移至頂部",
            "下移至底部": "下移至底部",
            "段落拖动": "段落拖動",
            "段落拖动开关说明": "開啟後段落可拖動重排。注意：拖動段落到歌詞編輯欄時可能把程式碼嵌入文字中，且與左滑刪除功能衝突。",
            "开启段落拖动功能？": "開啟段落拖動功能？",
            "我已知晓风险，继续开启": "我已知曉風險，繼續開啟",
            "拖动段落重排": "拖動段落重排",

        ],

        .english: [
                        "section.type.Intro": "Intro",
            "section.type.Verse": "Verse",
            "section.type.Pre-Chorus": "Pre-Chorus",
            "section.type.Chorus": "Chorus",
            "section.type.Post-Chorus": "Post-Chorus",
            "section.type.Bridge": "Bridge",
            "section.type.Hook": "Hook",
            "section.type.Refrain": "Refrain",
            "section.type.Interlude": "Interlude",
            "section.type.Solo": "Solo",
            "section.type.Outro": "Outro",
            "section.type.Coda": "Coda",
            "section.type.Custom": "Custom",
            "idea.type.Inspiration": "Inspiration",
            "idea.type.Setting": "Setting",
            "idea.type.Background": "Background",
            "idea.type.Note": "Note",
// ====== v1.5 新增 ======
            "笔记": "Notes",
            "更多": "More",
            "中文": "Chinese",
            "文件夹": "Folder",
            "新文件夹": "New Folder",
            "归并到文件夹": "Move to Folder",
            "重命名": "Rename",
            "解散文件夹": "Disband Folder",
            "备份文件夹": "Backup Folder",
            "导出文件夹": "Export Folder",
            "选中 %d 项": "%d selected",
            "已选中": "Selected",
            "取消选择": "Deselect",
            "选择歌曲": "Select Songs",
            "目标文件夹": "Target Folder",
            "新建文件夹": "Create Folder",
            "歌单": "Playlist",
            "歌曲类型": "Song Type",
            "回收站": "Trash",
            "移到回收站": "Move to Trash",
            "永久删除": "Delete Permanently",
            "将歌曲移到回收站": "Move song to Trash?",
            "将歌曲永久删除": "Delete song permanently? This cannot be undone!",
            "将文件夹永久删除": "Permanently delete folder and all songs inside? This cannot be undone!",
            "清空回收站": "Empty Trash",
            "在回收站中再次删除才能永久删除": "Delete again in Trash to remove permanently",
            "已选 %d 项": "%d selected",
            "已选 1 项": "1 selected",
            // ====== v1.6 节拍 / 文件夹操作 ======
            "节拍": "Beat",
            "节拍器": "Metronome",
            "停止": "Stop",
            "停止节拍器": "Stop metronome",
            "启动节拍器": "Start metronome",
            // ====== v1.7 歌词预览 / UI补充 ======
            "歌词预览": "Lyrics Preview",
            "预览歌词": "Preview Lyrics",
            "未命名歌曲": "Untitled",
            "未知艺术家": "Unknown Artist",
            "暂无歌词": "No lyrics yet",
            "双击跳转到段落": "Double-click to jump to section",
            "正在预览": "Previewing",
            "展开 / 收起元信息": "Show / Hide Metadata",

            "删除文件夹": "Delete Folder",
            "双击展开/折叠文件夹": "Double-click to expand/collapse",
            "确定要删除文件夹": "Delete this folder?",

            "备份曲目库（含文件夹结构）": "Backup library (with folders)",
            "导入文件夹": "Import Folder",
            // ====== v1.5.2 批量操作 ======
            "批量导出": "Batch Export",
            "批量移到回收站": "Move to Trash",
            "批量恢复": "Batch Restore",
            "批量永久删除": "Batch Delete Permanently",
            "批量移到根目录": "Move to Root",
            "移到根目录": "Move to Root",
            "移到其他文件夹": "Move to Other Folder",
            "批量移到其他文件夹": "Batch Move to Other Folder",
            "合并到新文件夹": "Merge to New Folder",
            "合并到文件夹": "Merge to Folder",
            "将 %d 首歌曲移到回收站？": "Move %d songs to Trash?",
            "导入 .smelody.txt 文件（可多选）": "Import .smelody.txt files (multiple)",
            "导入文件夹（不递归套娃，归到同名文件夹）": "Import folder (flat, to same-named folder)",
            "批量导入文件夹": "Batch Import Folder",
            "选择要导入的 .smelody.txt 文件（可多选）": "Select .smelody.txt files to import (multiple)",

            "导入备份文件夹（含套娃结构）": "Import backup folder (with nested structure)",
            "导入成功 (%d 首歌曲)": "Imported %d songs",
            "输入文件夹名": "Enter folder name",
            "输入新文件夹名": "Enter new folder name",
            "套娃文件夹": "Nested Folder",

"确定": "OK",
            "取消": "Cancel",
            "歌词导出": "Lyrics Export",
            "歌曲信息": "Song Info",
            "歌词": "Lyrics",
            "创建时间": "Created",
            "修改时间": "Modified",
            "导出时间": "Exported",
            "请先在歌曲语言中加入日语": "Please add Japanese to song languages first",
            "导出为文本文件（含全部信息）": "Export as Text File (with all info)",
            "将歌词的全部信息导出为文本文件": "Export all lyrics information to a text file",
            "导入歌曲": "Import Song",
            "导入歌曲文件": "Import Song File",
            "选择要导入的 .smelody.txt 文件": "Select .smelody.txt file to import",
            "导入成功": "Import Successful",
            "导入失败": "Import Failed",
            "数据管理": "Data Management",
            "一键备份曲目库": "One-Click Backup Library",
            "将所有歌曲按 .smelody.txt 格式打包到选定文件夹": "Package all songs as .smelody.txt to chosen folder",
            "备份": "Backup",
            "成功备份 %d 首歌曲到\n%@": "Successfully backed up %d songs to\n%@",
            "成功 %d 首，失败 %d 首": "%d succeeded, %d failed",
            "选择保存备份的文件夹": "Choose folder to save backup",
            "选择这里": "Choose",
            "删除前显示确认弹窗": "Show confirmation before delete",
            "删除歌曲、段落、灵感前提示确认（暂不可恢复）": "Confirm before deleting songs/sections/ideas (irreversible)",
            "确认删除": "Confirm Delete",
            "此操作暂不可恢复": "This action is irreversible",
            "不再提醒（可在设置中重新开启）": "Don't ask again (can re-enable in Settings)",
            "将删除歌曲": "Delete song",
            "将删除段落": "Delete section",
            "将删除条目": "Delete item",
            "将删除 %d 个段落": "Delete %d sections",
            "包含": "contains",
            "个段落": " sections",
            "条灵感与设定": " ideas and settings",
            "帮助": "Help",
            "下载链接": "Download Link",
            "更新日志": "Changelog",
            "查看更新日志": "View Changelog",
            "查看每个版本的更新内容": "View changes for each version",
            "使用指南": "Usage Guide",
            "技能炼成": "Skill Integrated",
            "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用": "Export Simple Melody's lyric Skills to an AI Agent",
            "词炼成": "Lyric Forge",
            "曲炼成": "Music Forge",
            "导出 Skill 文件": "Export Skill File",
            "复制到剪贴板": "Copy to Clipboard",
            "Skill 简介": "Skill Overview",
            "smelody-lyric-create": "smelody-lyric-create",
            "smelody-music-create": "smelody-music-create",
            "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）": "Creative needs → complete .smelody.txt (importable to Simple Melody)",
            "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）": ".smelody.txt → music AI input (SUNO / Udio)",
            "保存为": "Save as",
            "保存成功": "Save successful",
            "保存失败": "Save failed",
            "：找不到 SKILL.md 资源": ": SKILL.md resource not found",
            "复制成功": "Copy successful",
            "复制失败": "Copy failed",
            "选择保存位置": "Choose save location",
            "Skill 文件（.md）": "Skill file (.md)",
            "Skill 文件夹父目录": "Parent folder for Skill directory",
            "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。": "Lyric Forge turns creative needs into importable .smelody.txt lyric files for Simple Melody.",
            "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。": "Music Forge distills .smelody.txt into a two-section file ready for music AI (SUNO / Udio, etc.).",
            "典型工作流": "Typical workflow",
            "完整工作流（推荐）": "Full workflow (recommended)",
            "第一步：做词炼成": "Step 1: Lyric Forge",
            "第二步：做曲炼成": "Step 2: Music Forge",
            "第三步：交给 AI Agent 作曲": "Step 3: Hand off to AI Agent",
            "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）": "Send creative needs to AI Agent (with SUNO/Udio tools)",
            "描述歌曲主题、风格、参考等": "Describe song theme, style, references, etc.",
            "触发词：": "Trigger words:",
            "触发词": "Trigger words",
            "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"": "\"Do lyric forge\" / \"Write lyrics in smelody format\" / \"Write a song in Simple Melody format\"",
            "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"": "\"Do music forge\" / \"Prepare SUNO prompt\" / \"Prepare lyrics for AI composition\"",
            "输出": "Output",
            "把完整歌词文件保存为 .smelody.txt": "Save complete lyric file as .smelody.txt",
            "在 Simple Melody 中导入": "Import in Simple Melody",
            "把 .smelody.txt 歌词文件发给 AI Agent": "Send .smelody.txt lyric file to AI Agent",
            "AI 提炼出两段式输出文件": "AI distills into a two-section output file",
            "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框": "Paste the upper lyric section to SUNO / Udio's Lyrics input",
            "下半部分作曲建议作为 Style prompt 的一部分": "Use the lower section as part of Style prompt",
            "如果您无法理解以上内容请不要使用该功能": "If you cannot understand the above, please do not use this feature",
            "Skill 需要移交给拥有 Agent 能力的智能体": "Skills must be handed off to an Agent-capable AI",
            "否则无效": "otherwise invalid",
            "复制 Skill 文本": "Copy Skill text",
            "已复制到剪贴板": "Copied to clipboard",
            "词炼成：AI 输出完整 .smelody.txt": "Lyric Forge: AI outputs complete .smelody.txt",
            "曲炼成：AI 输出两段式（歌词 + 作曲建议）": "Music Forge: AI outputs two-section file (lyrics + composition hints)",
            "软件介绍 + 各功能使用说明（随界面语言切换）": "App introduction + feature usage guide",
            "最新": "Latest",
            "版本": "Version",
            "开发者": "Developer",
            "平台": "Platform",
            "Apple Silicon 原生": "Apple Silicon Native",
            "保存": "Save",
            "删除": "Delete",
            "编辑": "Edit",
            "新建": "New",
            "搜索": "Search",
            "关闭": "Close",
            "复制": "Copy",
            "粘贴": "Paste",
            "导出": "Export",
            "导入": "Import",

            "曲目库": "Songs",
            "首": "",
            "条记录": " entries",
            "搜索曲目": "Search songs",
            "新建歌曲": "New Song",
            "新建第一首": "New First Song",
            "新建段落": "New Section",
            "还没有歌曲": "No songs yet",
            "没有匹配的歌曲": "No matching songs",
            "选择左侧的歌曲开始创作，或新建一首新歌。": "Pick a song on the left to start writing, or create a new one.",
            "Simple Melody": "Simple Melody",

            "排序方式": "Sort",
            "手动排序": "Manual",
            "最近修改": "Recently Modified",
            "标题": "Title",

            "段": " sections",
            "字": " chars",
            "BPM": "BPM",
            "Key": "Key",
            "未命名": "Untitled",

            "歌曲标题": "Song Title",
            "艺术家": "Artist",
            "语言": "Language",
            "调式": "Key",
            "标签（逗号分隔）": "Tags (comma-separated)",
            "收起": "Collapse",
            "展开": "Expand",
            "导出为文本文件": "Export as Text File",
            "复制全文到剪贴板": "Copy All to Clipboard",
            "段落笔记": "Section Notes",
            "段落类型": "Section Type",
            "自定义段落名": "Custom Section Name",
            "应用": "Apply",
            "如 Spoken Word": "e.g. Spoken Word",
            "上移": "Move Up",
            "下移": "Move Down",
            "复制段落": "Duplicate Section",
            "上": "Up",
            "下": "Down",

            "前奏": "Intro",
            "主歌": "Verse",
            "预副歌": "Pre-Chorus",
            "副歌": "Chorus",
            "副歌后": "Post-Chorus",
            "桥段": "Bridge",
            "记忆点": "Hook",
            "叠句": "Refrain",
            "间奏": "Interlude",
            "独奏": "Solo",
            "尾奏": "Outro",
            "终曲": "Coda",
            "自定义": "Custom",
            "添加段落": "Add Section",

            "正文": "Body",
            "读音摘要": "Pronunciation Preview",
            "注音列表": "Annotations",
            "添加读音": "Add Reading",
            "自动注音": "Auto Furigana",
            "对日语汉字自动生成假名注音": "Generate furigana for kanji automatically",
            "为指定位置的文字添加读音": "Add reading for text at specified position",
            "清除注音选项": "Clear annotations",
            "清除所有自动注音": "Clear All Auto Annotations",
            "清除所有手动注音": "Clear All Manual Annotations",
            "在正文中的位置": "Position in body",
            "起始: %d": "Start: %d",
            "长度: %d": "Length: %d",
            "原文预览": "Original Preview",
            "原文": "Original",
            "假名读音": "Furigana",
            "拼音": "Pinyin",
            "Phonetic": "Phonetic",
            "编辑读音": "Edit Reading",
            "自动标注日语假音": "Auto-annotate Japanese furigana",

            "灵感与设定": "Ideas & Settings",
            "灵感": "Inspiration",
            "设定": "Setting",
            "背景": "Background",
            "备注": "Note",
            "全部": "All",
            "记录灵感、背景故事、设定...": "Record inspiration, background, settings...",
            "还没有灵感或设定": "No ideas or settings yet",
            "在这里记录创作灵感、角色设定或背景故事。": "Record your creative inspiration, character settings or background story here.",
            "这些内容不会出现在歌词正文里。": "These won't appear in the lyrics body.",

            "设置": "Settings",
            "主题": "Theme",
            "跟随系统": "Follow System",
            "浅色": "Light",
            "深色": "Dark",
            "界面语言": "Interface Language",
            "首选语言": "Preferred Language",
            "歌曲语言（可多选）": "Song Languages (multiple)",

            "日语": "Japanese",
            "简体中文": "Simplified Chinese",
            "繁体中文": "Traditional Chinese",
            "英语": "English",
            "韩语": "Korean",
            "西班牙语": "Spanish",
            "法语": "French",
            "德语": "German",
            "意大利语": "Italian",
            "葡萄牙语": "Portuguese",
            "选择语言": "Select Languages",
            "已选": "Selected",
            "未选": "Unselected",
            "歌词语言": "Lyrics Language",
            "自动识别系统语言": "Auto-detect system language",
            "应用启动时检测系统语言": "Detect system language on launch",

            "Simple Melody 帮助": "Simple Melody Help",

            "暂无帮助文档，请查看 README.md": "No help document. See README.md",

            "关于 Simple Melody": "About Simple Melody",
            "v1.1 · Apple Silicon Native": "v1.1 · Apple Silicon Native",

            "灵感分栏": "Ideas Panel",
            "显示/隐藏灵感与设定分栏": "Show/hide ideas and settings panel",
            "专辑": "Album",
            "从 .smelody.txt 文件导入歌曲": "Import song from .smelody.txt file",
            "副本": "Copy",
            "备份曲目库": "Backup Library",
            "导出歌词": "Export Lyrics",
            "将删除注音": "Delete annotation",
            "将清除 %d 条手动注音": "Clear %d manual annotations",
            "将清除 %d 条自动注音": "Clear %d auto annotations",
            "将覆盖 %d 条现有的自动注音": "Will overwrite %d existing auto annotations",
            "展开元信息": "Show metadata",
            "展开元信息（语言/BPM/调式/标签）": "Show metadata (language/BPM/key/tags)",
            "折叠": "Collapse",
            "文件格式无效": "Invalid file format",
            "新歌曲": "New Song",
            "标签": "Tags",
            "缺少歌曲元信息": "Missing song metadata",
            "自动注音（仅日语段落）": "Auto Furigana (Japanese sections only)",
            "读取失败": "Read failed",
            "重新生成自动注音": "Regenerate Auto Furigana",
            "长按段落任意位置可拖动重排": "Long-press anywhere on a section to drag and reorder",
            "上移至顶部": "Move to Top",
            "下移至底部": "Move to Bottom",
            "段落拖动": "Section Drag",
            "段落拖动开关说明": "Enabling allows reordering sections by drag. Note: dragging sections over the lyrics editor may embed code snippets into the text, and conflicts with swipe-to-delete.",
            "开启段落拖动功能？": "Enable Section Drag?",
            "我已知晓风险，继续开启": "I understand the risks, enable",
            "拖动段落重排": "Drag sections to reorder",

        ],

        .japanese: [
                        "section.type.Intro": "イントロ",
            "section.type.Verse": "Aメロ",
            "section.type.Pre-Chorus": "Preコーラス",
            "section.type.Chorus": "サビ",
            "section.type.Post-Chorus": "Postコーラス",
            "section.type.Bridge": "ブリッジ",
            "section.type.Hook": "フック",
            "section.type.Refrain": "リフレイン",
            "section.type.Interlude": "間奏",
            "section.type.Solo": "ソロ",
            "section.type.Outro": "アウトロ",
            "section.type.Coda": "コーダ",
            "section.type.Custom": "カスタム",
            "idea.type.Inspiration": "インスピレーション",
            "idea.type.Setting": "設定",
            "idea.type.Background": "背景",
            "idea.type.Note": "メモ",
// ====== v1.5 新增 ======
            "笔记": "メモ",
            "更多": "その他",
            "中文": "中国語",
            "文件夹": "フォルダ",
            "新文件夹": "新規フォルダ",
            "归并到文件夹": "フォルダに移動",
            "重命名": "名前を変更",
            "解散文件夹": "フォルダを解散",
            "备份文件夹": "フォルダをバックアップ",
            "导出文件夹": "フォルダをエクスポート",
            "选中 %d 项": "%d 件選択中",
            "已选中": "選択済み",
            "取消选择": "選択解除",
            "选择歌曲": "楽曲を選択",
            "目标文件夹": "対象フォルダ",
            "新建文件夹": "フォルダを作成",
            "歌单": "プレイリスト",
            "歌曲类型": "楽曲タイプ",
            "回收站": "ゴミ箱",
            "移到回收站": "ゴミ箱へ移動",
            "永久删除": "完全に削除",
            "将歌曲移到回收站": "楽曲をゴミ箱へ移動しますか？",
            "将歌曲永久删除": "楽曲を完全に削除しますか？この操作は元に戻せません！",
            "将文件夹永久删除": "フォルダと内部の楽曲をすべて完全に削除しますか？この操作は元に戻せません！",
            "清空回收站": "ゴミ箱を空にする",
            "在回收站中再次删除才能永久删除": "完全に削除するにはゴミ箱でもう一度削除してください",
            "已选 %d 项": "%d 件選択中",
            "已选 1 项": "1 件選択中",
            // ====== v1.6 节拍 / 文件夹操作 ======
            "节拍": "拍子",
            "节拍器": "メトロノーム",
            "停止": "停止",
            "停止节拍器": "メトロノームを停止",
            "启动节拍器": "メトロノームを開始",
            // ====== v1.7 歌词预览 / UI补充 ======
            "歌词预览": "歌詞プレビュー",
            "预览歌词": "歌詞をプレビュー",
            "未命名歌曲": "無題の曲",
            "未知艺术家": "不明なアーティスト",
            "暂无歌词": "歌詞はまだありません",
            "双击跳转到段落": "ダブルクリックでセクションにジャンプ",
            "正在预览": "プレビュー中",
            "展开 / 收起元信息": "メタ情報を表示 / 非表示",

            "删除文件夹": "フォルダを削除",
            "双击展开/折叠文件夹": "ダブルクリックで展開/折りたたみ",
            "确定要删除文件夹": "フォルダを削除しますか？",

            "备份曲目库（含文件夹结构）": "ライブラリをバックアップ（フォルダ構造を含む）",
            "导入文件夹": "フォルダをインポート",
            // ====== v1.5.2 批量操作 ======
            "批量备份": "一括バックアップ",
            "批量导出": "一括エクスポート",
            "批量移到回收站": "ゴミ箱へ一括移動",
            "批量恢复": "一括復元",
            "批量永久删除": "一括完全削除",
            "批量移到根目录": "ルートへ一括移動",
            "移到根目录": "ルートに移動",
            "移到其他文件夹": "別のフォルダに移動",
            "批量移到其他文件夹": "一括で別のフォルダに移動",
            "合并到新文件夹": "新規フォルダにマージ",
            "合并到文件夹": "フォルダにマージ",
            "将 %d 首歌曲移到回收站？": "%d 曲をゴミ箱へ移動しますか？",
            "导入 .smelody.txt 文件（可多选）": ".smelody.txt ファイルをインポート（複数選択可）",
            "导入文件夹（不递归套娃，归到同名文件夹）": "フォルダをインポート（再帰なし、同名フォルダへ）",
            "批量导入文件夹": "一括フォルダインポート",
            "选择要导入的 .smelody.txt 文件（可多选）": "インポートする .smelody.txt ファイルを選択（複数可）",

            "导入备份文件夹（含套娃结构）": "バックアップフォルダをインポート（入れ子構造を含む）",
            "导入成功 (%d 首歌曲)": "%d 曲をインポートしました",
            "输入文件夹名": "フォルダ名を入力",
            "输入新文件夹名": "新しいフォルダ名を入力",
            "套娃文件夹": "入れ子フォルダ",

"确定": "OK",
            "取消": "キャンセル",
            "歌词导出": "歌詞エクスポート",
            "歌曲信息": "楽曲情報",
            "歌词": "歌詞",
            "创建时间": "作成日時",
            "修改时间": "更新日時",
            "导出时间": "エクスポート日時",
            "请先在歌曲语言中加入日语": "まず楽曲の言語に日本語を追加してください",
            "导出为文本文件（含全部信息）": "テキストファイルでエクスポート（全情報を含む）",
            "将歌词的全部信息导出为文本文件": "歌詞の全情報をテキストファイルにエクスポート",
            "导入歌曲": "曲をインポート",
            "导入歌曲文件": "曲ファイルをインポート",
            "选择要导入的 .smelody.txt 文件": "インポートする .smelody.txt ファイルを選択",
            "导入成功": "インポート成功",
            "导入失败": "インポート失敗",
            "数据管理": "データ管理",
            "一键备份曲目库": "楽曲ライブラリを一括バックアップ",
            "将所有歌曲按 .smelody.txt 格式打包到选定文件夹": "すべての曲を .smelody.txt で選択フォルダに書き出し",
            "备份": "バックアップ",
            "成功备份 %d 首歌曲到\n%@": "%d 曲をバックアップしました\n%@",
            "成功 %d 首，失败 %d 首": "%d 曲成功、%d 曲失敗",
            "选择保存备份的文件夹": "バックアップ保存フォルダを選択",
            "选择这里": "選択",
            "删除前显示确认弹窗": "削除前に確認ダイアログを表示",
            "删除歌曲、段落、灵感前提示确认（暂不可恢复）": "曲/セクション/アイデアの削除前に確認（復元不可）",
            "确认删除": "削除を確認",
            "此操作暂不可恢复": "この操作は復元できません",
            "不再提醒（可在设置中重新开启）": "次回から表示しない（設定で再有効化可能）",
            "将删除歌曲": "曲を削除",
            "将删除段落": "セクションを削除",
            "将删除条目": "項目を削除",
            "将删除 %d 个段落": "%d 個のセクションを削除",
            "包含": "含む",
            "个段落": " セクション",
            "条灵感与设定": " 件のアイデア・設定",
            "帮助": "ヘルプ",
            "下载链接": "ダウンロードリンク",
            "更新日志": "更新履歴",
            "查看更新日志": "更新履歴を見る",
            "使用指南": "使い方ガイド",
            "技能炼成": "スキル錬成",
            "把 Simple Melody 的歌词 Skill 导出给 AI Agent 用": "Simple Melody の歌詞 Skill を AI Agent にエクスポート",
            "词炼成": "詞錬成",
            "曲炼成": "曲錬成",
            "导出 Skill 文件": "Skill ファイルをエクスポート",
            "复制到剪贴板": "クリップボードにコピー",
            "Skill 简介": "Skill 概要",
            "smelody-lyric-create": "smelody-lyric-create",
            "smelody-music-create": "smelody-music-create",
            "把创作需求 → 完整的 .smelody.txt（可导入 Simple Melody）": "創作ニーズ → 完全な .smelody.txt（Simple Melody にインポート可能）",
            "把 .smelody.txt → 作曲 AI 输入（SUNO / Udio）": ".smelody.txt → 作曲 AI 入力（SUNO / Udio）",
            "保存为": "名前を付けて保存",
            "保存成功": "保存成功",
            "保存失败": "保存失敗",
            "：找不到 SKILL.md 资源": "：SKILL.md リソースが見つかりません",
            "复制成功": "コピー成功",
            "复制失败": "コピー失敗",
            "选择保存位置": "保存場所を選択",
            "Skill 文件（.md）": "Skill ファイル（.md）",
            "Skill 文件夹父目录": "Skill フォルダの親ディレクトリ",
            "词炼成是把创作需求转化为可导入 Simple Melody 的 .smelody.txt 歌词文件。": "詞錬成は創作ニーズを Simple Melody にインポート可能な .smelody.txt 歌詞ファイルに変換します。",
            "曲炼成是把 .smelody.txt 提炼为作曲 AI（SUNO / Udio 等）可直接使用的两段式文件。": "曲錬成は .smelody.txt を作曲 AI（SUNO / Udio など）が直接使用できる二段組ファイルに提炼します。",
            "典型工作流": "典型的なワークフロー",
            "完整工作流（推荐）": "完全なワークフロー（推奨）",
            "第一步：做词炼成": "ステップ 1：詞錬成",
            "第二步：做曲炼成": "ステップ 2：曲錬成",
            "第三步：交给 AI Agent 作曲": "ステップ 3：AI Agent に作曲を任せる",
            "把创作需求发给 AI Agent（如有 SUNO/Udio 工具）": "創作ニーズを AI Agent（SUNO/Udio ツール付き）に送信",
            "描述歌曲主题、风格、参考等": "曲のテーマ、スタイル、参考資料などを記述",
            "触发词：": "トリガーワード：",
            "触发词": "トリガーワード",
            "\"做词炼成\" / \"按 smelody 格式写歌词\" / \"写一首 Simple Melody 格式的歌词\"": "\"詞錬成を実行\" / \"smelody 形式で歌詞を書く\" / \"Simple Melody 形式の歌詞を書く\"",
            "\"做曲炼成\" / \"准备 SUNO 提示词\" / \"整理歌词给 AI 作曲\"": "\"曲錬成を実行\" / \"SUNO プロンプトを準備\" / \"AI 作曲用に歌詞を整理\"",
            "输出": "出力",
            "把完整歌词文件保存为 .smelody.txt": "完全な歌詞ファイルを .smelody.txt として保存",
            "在 Simple Melody 中导入": "Simple Melody でインポート",
            "把 .smelody.txt 歌词文件发给 AI Agent": ".smelody.txt 歌詞ファイルを AI Agent に送信",
            "AI 提炼出两段式输出文件": "AI が二段組出力ファイルに提炼",
            "上半部分歌词粘贴到 SUNO / Udio 的 Lyrics 输入框": "上部の歌詞を SUNO / Udio の Lyrics 入力欄に貼り付け",
            "下半部分作曲建议作为 Style prompt 的一部分": "下部の作曲提案を Style prompt の一部として使用",
            "如果您无法理解以上内容请不要使用该功能": "上記の内容が理解できない場合は、この機能を使用しないでください",
            "Skill 需要移交给拥有 Agent 能力的智能体": "Skill は Agent 能力を持つ AI に引き渡す必要があります",
            "否则无效": "さもないと無効です",
            "复制 Skill 文本": "Skill テキストをコピー",
            "已复制到剪贴板": "クリップボードにコピーしました",
            "词炼成：AI 输出完整 .smelody.txt": "詞錬成：AI は完全な .smelody.txt を出力",
            "曲炼成：AI 输出两段式（歌词 + 作曲建议）": "曲錬成：AI は二段組ファイル（歌詞 + 作曲提案）を出力",
            "软件介绍 + 各功能使用说明（随界面语言切换）": "アプリ紹介 + 各機能の使い方ガイド",
            "查看每个版本的更新内容": "各バージョンの更新内容を見る",
            "最新": "最新",
            "版本": "バージョン",
            "开发者": "開発者",
            "平台": "プラットフォーム",
            "Apple Silicon 原生": "Apple Silicon ネイティブ",
            "保存": "保存",
            "删除": "削除",
            "编辑": "編集",
            "新建": "新規",
            "搜索": "検索",
            "关闭": "閉じる",
            "复制": "コピー",
            "粘贴": "貼り付け",
            "导出": "エクスポート",
            "导入": "インポート",

            "曲目库": "楽曲ライブラリ",
            "首": "曲",
            "条记录": "件",
            "搜索曲目": "楽曲を検索",
            "新建歌曲": "新しい曲",
            "新建第一首": "最初の曲を作る",
            "新建段落": "新しいセクション",
            "还没有歌曲": "曲がまだありません",
            "没有匹配的歌曲": "一致する曲がありません",
            "选择左侧的歌曲开始创作，或新建一首新歌。": "左側で曲を選ぶか、新しい曲を作成してください。",
            "Simple Melody": "Simple Melody",

            "排序方式": "並び替え",
            "手动排序": "手動",
            "最近修改": "最近更新",
            "标题": "タイトル",

            "段": "セクション",
            "字": "文字",
            "BPM": "BPM",
            "Key": "キー",
            "未命名": "無題",

            "歌曲标题": "曲のタイトル",
            "艺术家": "アーティスト",
            "语言": "言語",
            "调式": "キー",
            "标签（逗号分隔）": "タグ（カンマ区切り）",
            "收起": "折りたたむ",
            "展开": "展開",
            "导出为文本文件": "テキストファイルでエクスポート",
            "复制全文到剪贴板": "全文をクリップボードにコピー",
            "段落笔记": "セクションのメモ",
            "段落类型": "セクションタイプ",
            "自定义段落名": "カスタムセクション名",
            "应用": "適用",
            "如 Spoken Word": "例: Spoken Word",
            "上移": "上へ",
            "下移": "下へ",
            "复制段落": "セクションを複製",
            "上": "上",
            "下": "下",

            "前奏": "イントロ",
            "主歌": "Aメロ",
            "预副歌": "プレコーラス",
            "副歌": "サビ",
            "副歌后": "ポストコーラス",
            "桥段": "ブリッジ",
            "记忆点": "フック",
            "叠句": "リフレイン",
            "间奏": "間奏",
            "独奏": "ソロ",
            "尾奏": "アウトロ",
            "终曲": "コーダ",
            "自定义": "カスタム",
            "添加段落": "セクションを追加",

            "正文": "本文",
            "读音摘要": "ふりがなプレビュー",
            "注音列表": "ふりがなリスト",
            "添加读音": "ふりがなを追加",
            "自动注音": "自動ふりがな",
            "对日语汉字自动生成假名注音": "漢字に自動でふりがなを生成",
            "为指定位置的文字添加读音": "指定位置の文字にふりがなを追加",
            "清除注音选项": "ふりがなをクリア",
            "清除所有自动注音": "自動ふりがなを全て削除",
            "清除所有手动注音": "手動ふりがなを全て削除",
            "在正文中的位置": "本文中の位置",
            "起始: %d": "開始: %d",
            "长度: %d": "長さ: %d",
            "原文预览": "原文プレビュー",
            "原文": "原文",
            "假名读音": "ふりがな",
            "拼音": "拼音",
            "Phonetic": "Phonetic",
            "编辑读音": "ふりがなを編集",
            "自动标注日语假音": "日本語の漢字に自動でふりがなを付ける",

            "灵感与设定": "インスピレーション・設定",
            "灵感": "インスピレーション",
            "设定": "設定",
            "背景": "背景",
            "备注": "メモ",
            "全部": "すべて",
            "记录灵感、背景故事、设定...": "インスピレーション、背景、設定を記録...",
            "还没有灵感或设定": "インスピレーションや設定がまだありません",
            "在这里记录创作灵感、角色设定或背景故事。": "ここに創作のインスピレーションやキャラクター設定、背景を記録してください。",
            "这些内容不会出现在歌词正文里。": "これらは歌詞の本文には表示されません。",

            "设置": "設定",
            "主题": "テーマ",
            "跟随系统": "システムに合わせる",
            "浅色": "ライト",
            "深色": "ダーク",
            "界面语言": "インターフェース言語",
            "首选语言": "優先言語",
            "歌曲语言（可多选）": "曲の言語（複数選択可）",

            "日语": "日本語",
            "简体中文": "簡体中国語",
            "繁体中文": "繁体中国語",
            "英语": "英語",
            "韩语": "韓国語",
            "西班牙语": "スペイン語",
            "法语": "フランス語",
            "德语": "ドイツ語",
            "意大利语": "イタリア語",
            "葡萄牙语": "ポルトガル語",
            "选择语言": "言語を選択",
            "已选": "選択済み",
            "未选": "未選択",
            "歌词语言": "歌詞の言語",
            "自动识别系统语言": "システム言語を自動検出",
            "应用启动时检测系统语言": "起動時にシステム言語を検出",

            "Simple Melody 帮助": "Simple Melody ヘルプ",

            "暂无帮助文档，请查看 README.md": "ヘルプドキュメントはありません。README.md を参照してください。",

            "关于 Simple Melody": "Simple Melody について",
            "v1.1 · Apple Silicon Native": "v1.1 · Apple Silicon Native",

            "灵感分栏": "アイデアパネル",
            "显示/隐藏灵感与设定分栏": "アイデア・設定パネルの表示/非表示",
            "专辑": "アルバム",
            "从 .smelody.txt 文件导入歌曲": ".smelody.txt ファイルから曲をインポート",
            "副本": "コピー",
            "备份曲目库": "ライブラリをバックアップ",
            "导出歌词": "歌詞をエクスポート",
            "将删除注音": "ふりがなを削除",
            "将清除 %d 条手动注音": "手動ふりがな %d 件を削除",
            "将清除 %d 条自动注音": "自動ふりがな %d 件を削除",
            "将覆盖 %d 条现有的自动注音": "既存の自動ふりがな %d 件を上書きします",
            "展开元信息": "メタデータを展開",
            "展开元信息（语言/BPM/调式/标签）": "メタデータを展開（言語/BPM/キー/タグ）",
            "折叠": "折りたたむ",
            "文件格式无效": "ファイル形式が無効",
            "新歌曲": "新しい曲",
            "标签": "タグ",
            "缺少歌曲元信息": "楽曲のメタデータが不足",
            "自动注音（仅日语段落）": "自動ふりがな（日本語セクションのみ）",
            "读取失败": "読み込み失敗",
            "重新生成自动注音": "自動ふりがなを再生成",
            "长按段落任意位置可拖动重排": "セクションの任意の場所を長押しでドラッグ並び替え",
            "上移至顶部": "一番上に移動",
            "下移至底部": "一番下に移動",
            "段落拖动": "セクションドラッグ",
            "段落拖动开关说明": "有効化するとセクションをドラッグで並び替えできます。注意：歌詞エディタにセクションをドラッグするとコードがテキストに埋め込まれる可能性があり、スワイプ削除機能と競合します。",
            "开启段落拖动功能？": "セクションドラッグを有効にしますか？",
            "我已知晓风险，继续开启": "リスクを理解した上で有効にする",
            "拖动段落重排": "セクションをドラッグして並べ替え",

        ],
    ]
}
